/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.nio.charset.StandardCharsets;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    static {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.AuthenticationInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.AuthenticationValue.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.AuthorizationsIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.BulkQuotesIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.BulkQuotesPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.BulkTransfersIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.BulkTransfersPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformationObject.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformationResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.Extension.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.ExtensionList.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxCharge.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxConversion.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxMoney.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxQuotesIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxQuotesPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxRate.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxTransfersIDPatchResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxTransfersIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxTransfersPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.GeoCode.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.IndividualQuote.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.IndividualQuoteResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.IndividualTransfer.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.IndividualTransferResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.Money.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.ParticipantsIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.ParticipantsPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.ParticipantsTypeIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.ParticipantsTypeIDSubIDPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.PartiesTypeIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.Party.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.PartyComplexName.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.PartyIdInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.PartyPersonalInfo.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.PartyResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.QuotesIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.QuotesPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.Refund.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.ServicesFXPPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.ServicesFXPSourceCurrencyTargetCurrencyPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.Transaction.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransactionRequestsIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransactionRequestsPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransactionType.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransactionsIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransfersIDPatchResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransfersIDPutResponse.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransfersPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.thitsaworks.mojaloop.coreconnector.fspiop.model.U2FPinValue.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
    * Deserialize the given JSON InputStream to a Java object.
    *
    * @param <T>         Type
    * @param inputStream The JSON InputStream
    * @param returnType  The type to deserialize into
    * @return The deserialized Java object
    */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(InputStream inputStream, Type returnType) throws IOException {
        try (InputStreamReader reader = new InputStreamReader(inputStream, StandardCharsets.UTF_8)) {
        if (isLenientOnJson) {
            // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
            JsonReader jsonReader = new JsonReader(reader);
            jsonReader.setLenient(true);
            return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(reader, returnType);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
