/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.Money;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FxCharge
 */
public class FxChargeTest {
    private final FxCharge model = new FxCharge();

    /**
     * Model tests for FxCharge
     */
    @Test
    public void testFxCharge() {
        // TODO: test FxCharge
    }

    /**
     * Test the property 'chargeType'
     */
    @Test
    public void chargeTypeTest() {
        // TODO: test chargeType
    }

    /**
     * Test the property 'sourceAmount'
     */
    @Test
    public void sourceAmountTest() {
        // TODO: test sourceAmount
    }

    /**
     * Test the property 'targetAmount'
     */
    @Test
    public void targetAmountTest() {
        // TODO: test targetAmount
    }

}
