/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ExtensionList;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.GeoCode;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.Money;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QuotesIDPutResponse
 */
public class QuotesIDPutResponseTest {
    private final QuotesIDPutResponse model = new QuotesIDPutResponse();

    /**
     * Model tests for QuotesIDPutResponse
     */
    @Test
    public void testQuotesIDPutResponse() {
        // TODO: test QuotesIDPutResponse
    }

    /**
     * Test the property 'transferAmount'
     */
    @Test
    public void transferAmountTest() {
        // TODO: test transferAmount
    }

    /**
     * Test the property 'payeeReceiveAmount'
     */
    @Test
    public void payeeReceiveAmountTest() {
        // TODO: test payeeReceiveAmount
    }

    /**
     * Test the property 'payeeFspFee'
     */
    @Test
    public void payeeFspFeeTest() {
        // TODO: test payeeFspFee
    }

    /**
     * Test the property 'payeeFspCommission'
     */
    @Test
    public void payeeFspCommissionTest() {
        // TODO: test payeeFspCommission
    }

    /**
     * Test the property 'expiration'
     */
    @Test
    public void expirationTest() {
        // TODO: test expiration
    }

    /**
     * Test the property 'geoCode'
     */
    @Test
    public void geoCodeTest() {
        // TODO: test geoCode
    }

    /**
     * Test the property 'ilpPacket'
     */
    @Test
    public void ilpPacketTest() {
        // TODO: test ilpPacket
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'extensionList'
     */
    @Test
    public void extensionListTest() {
        // TODO: test extensionList
    }

}
