/*
 * Copyright (c) 2024-2026 ThitsaWorks Pte. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.api;

import com.thitsaworks.mojaloop.coreconnector.fspiop.ApiCallback;
import com.thitsaworks.mojaloop.coreconnector.fspiop.ApiClient;
import com.thitsaworks.mojaloop.coreconnector.fspiop.ApiException;
import com.thitsaworks.mojaloop.coreconnector.fspiop.ApiResponse;
import com.thitsaworks.mojaloop.coreconnector.fspiop.Configuration;
import com.thitsaworks.mojaloop.coreconnector.fspiop.Pair;
import com.thitsaworks.mojaloop.coreconnector.fspiop.ProgressRequestBody;
import com.thitsaworks.mojaloop.coreconnector.fspiop.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.thitsaworks.mojaloop.coreconnector.fspiop.model.AuthorizationsIDPutResponse;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformationObject;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformationResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AuthorizationsApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AuthorizationsApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AuthorizationsApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for authorizationsByIDAndError
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param errorInformationObject Details of the error returned. (required)
     * @param contentLength The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes). (optional)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call authorizationsByIDAndErrorCall(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull ErrorInformationObject errorInformationObject, @javax.annotation.Nullable Integer contentLength, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = errorInformationObject;

        // create path and map variables
        String localVarPath = "/authorizations/{ID}/error"
            .replace("{" + "ID" + "}", localVarApiClient.escapeString(ID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (contentLength != null) {
            localVarHeaderParams.put("Content-Length", localVarApiClient.parameterToString(contentLength));
        }


        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        if (date != null) {
            localVarHeaderParams.put("Date", localVarApiClient.parameterToString(date));
        }


        if (xForwardedFor != null) {
            localVarHeaderParams.put("X-Forwarded-For", localVarApiClient.parameterToString(xForwardedFor));
        }


        if (fsPIOPSource != null) {
            localVarHeaderParams.put("FSPIOP-Source", localVarApiClient.parameterToString(fsPIOPSource));
        }


        if (fsPIOPDestination != null) {
            localVarHeaderParams.put("FSPIOP-Destination", localVarApiClient.parameterToString(fsPIOPDestination));
        }


        if (fsPIOPEncryption != null) {
            localVarHeaderParams.put("FSPIOP-Encryption", localVarApiClient.parameterToString(fsPIOPEncryption));
        }


        if (fsPIOPSignature != null) {
            localVarHeaderParams.put("FSPIOP-Signature", localVarApiClient.parameterToString(fsPIOPSignature));
        }


        if (FSPIOP_URI != null) {
            localVarHeaderParams.put("FSPIOP-URI", localVarApiClient.parameterToString(FSPIOP_URI));
        }


        if (fsPIOPHTTPMethod != null) {
            localVarHeaderParams.put("FSPIOP-HTTP-Method", localVarApiClient.parameterToString(fsPIOPHTTPMethod));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call authorizationsByIDAndErrorValidateBeforeCall(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull ErrorInformationObject errorInformationObject, @javax.annotation.Nullable Integer contentLength, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ID' is set
        if (ID == null) {
            throw new ApiException("Missing the required parameter 'ID' when calling authorizationsByIDAndError(Async)");
        }

        // verify the required parameter 'contentType' is set
        if (contentType == null) {
            throw new ApiException("Missing the required parameter 'contentType' when calling authorizationsByIDAndError(Async)");
        }

        // verify the required parameter 'date' is set
        if (date == null) {
            throw new ApiException("Missing the required parameter 'date' when calling authorizationsByIDAndError(Async)");
        }

        // verify the required parameter 'fsPIOPSource' is set
        if (fsPIOPSource == null) {
            throw new ApiException("Missing the required parameter 'fsPIOPSource' when calling authorizationsByIDAndError(Async)");
        }

        // verify the required parameter 'errorInformationObject' is set
        if (errorInformationObject == null) {
            throw new ApiException("Missing the required parameter 'errorInformationObject' when calling authorizationsByIDAndError(Async)");
        }

        return authorizationsByIDAndErrorCall(ID, contentType, date, fsPIOPSource, errorInformationObject, contentLength, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, _callback);

    }

    /**
     * Return authorization error
     * If the server is unable to find the transaction request, or another processing error occurs, the error callback &#x60;PUT /authorizations/{ID}/error&#x60; is used. The &#x60;{ID}&#x60; in the URI should contain the &#x60;{ID}&#x60; that was used in the &#x60;GET /authorizations/{ID}&#x60;.
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param errorInformationObject Details of the error returned. (required)
     * @param contentLength The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes). (optional)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public void authorizationsByIDAndError(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull ErrorInformationObject errorInformationObject, @javax.annotation.Nullable Integer contentLength, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod) throws ApiException {
        authorizationsByIDAndErrorWithHttpInfo(ID, contentType, date, fsPIOPSource, errorInformationObject, contentLength, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod);
    }

    /**
     * Return authorization error
     * If the server is unable to find the transaction request, or another processing error occurs, the error callback &#x60;PUT /authorizations/{ID}/error&#x60; is used. The &#x60;{ID}&#x60; in the URI should contain the &#x60;{ID}&#x60; that was used in the &#x60;GET /authorizations/{ID}&#x60;.
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param errorInformationObject Details of the error returned. (required)
     * @param contentLength The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes). (optional)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<Void> authorizationsByIDAndErrorWithHttpInfo(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull ErrorInformationObject errorInformationObject, @javax.annotation.Nullable Integer contentLength, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod) throws ApiException {
        okhttp3.Call localVarCall = authorizationsByIDAndErrorValidateBeforeCall(ID, contentType, date, fsPIOPSource, errorInformationObject, contentLength, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Return authorization error (asynchronously)
     * If the server is unable to find the transaction request, or another processing error occurs, the error callback &#x60;PUT /authorizations/{ID}/error&#x60; is used. The &#x60;{ID}&#x60; in the URI should contain the &#x60;{ID}&#x60; that was used in the &#x60;GET /authorizations/{ID}&#x60;.
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param errorInformationObject Details of the error returned. (required)
     * @param contentLength The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes). (optional)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call authorizationsByIDAndErrorAsync(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull ErrorInformationObject errorInformationObject, @javax.annotation.Nullable Integer contentLength, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = authorizationsByIDAndErrorValidateBeforeCall(ID, contentType, date, fsPIOPSource, errorInformationObject, contentLength, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for authorizationsByIDGet
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use. (required)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call authorizationsByIDGetCall(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull String accept, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/authorizations/{ID}"
            .replace("{" + "ID" + "}", localVarApiClient.escapeString(ID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        if (date != null) {
            localVarHeaderParams.put("Date", localVarApiClient.parameterToString(date));
        }


        if (xForwardedFor != null) {
            localVarHeaderParams.put("X-Forwarded-For", localVarApiClient.parameterToString(xForwardedFor));
        }


        if (fsPIOPSource != null) {
            localVarHeaderParams.put("FSPIOP-Source", localVarApiClient.parameterToString(fsPIOPSource));
        }


        if (fsPIOPDestination != null) {
            localVarHeaderParams.put("FSPIOP-Destination", localVarApiClient.parameterToString(fsPIOPDestination));
        }


        if (fsPIOPEncryption != null) {
            localVarHeaderParams.put("FSPIOP-Encryption", localVarApiClient.parameterToString(fsPIOPEncryption));
        }


        if (fsPIOPSignature != null) {
            localVarHeaderParams.put("FSPIOP-Signature", localVarApiClient.parameterToString(fsPIOPSignature));
        }


        if (FSPIOP_URI != null) {
            localVarHeaderParams.put("FSPIOP-URI", localVarApiClient.parameterToString(FSPIOP_URI));
        }


        if (fsPIOPHTTPMethod != null) {
            localVarHeaderParams.put("FSPIOP-HTTP-Method", localVarApiClient.parameterToString(fsPIOPHTTPMethod));
        }


        if (accept != null) {
            localVarHeaderParams.put("Accept", localVarApiClient.parameterToString(accept));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call authorizationsByIDGetValidateBeforeCall(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull String accept, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ID' is set
        if (ID == null) {
            throw new ApiException("Missing the required parameter 'ID' when calling authorizationsByIDGet(Async)");
        }

        // verify the required parameter 'contentType' is set
        if (contentType == null) {
            throw new ApiException("Missing the required parameter 'contentType' when calling authorizationsByIDGet(Async)");
        }

        // verify the required parameter 'date' is set
        if (date == null) {
            throw new ApiException("Missing the required parameter 'date' when calling authorizationsByIDGet(Async)");
        }

        // verify the required parameter 'fsPIOPSource' is set
        if (fsPIOPSource == null) {
            throw new ApiException("Missing the required parameter 'fsPIOPSource' when calling authorizationsByIDGet(Async)");
        }

        // verify the required parameter 'accept' is set
        if (accept == null) {
            throw new ApiException("Missing the required parameter 'accept' when calling authorizationsByIDGet(Async)");
        }

        return authorizationsByIDGetCall(ID, contentType, date, fsPIOPSource, accept, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, _callback);

    }

    /**
     * Perform authorization
     * The HTTP request &#x60;GET /authorizations/{ID}&#x60; is used to request the Payer to enter the applicable credentials in the Payee FSP system. The &#x60;{ID}&#x60; in the URI should contain the &#x60;transactionRequestID&#x60;, received from the &#x60;POST /transactionRequests&#x60; service earlier in the process. This request requires a query string to be included in the URI, with the following key-value pairs*:*  - &#x60;authenticationType&#x3D;{Type}&#x60;, where &#x60;{Type}&#x60; value is a valid authentication type from the enumeration &#x60;AuthenticationType&#x60;.  - &#x60;retriesLeft&#x3D;&#x3D;{NrOfRetries}&#x60;, where &#x60;{NrOfRetries}&#x60; is the number of retries left before the financial transaction is rejected. &#x60;{NrOfRetries}&#x60; must be expressed in the form of the data type &#x60;Integer&#x60;. &#x60;retriesLeft&#x3D;1&#x60; means that this is the last retry before the financial transaction is rejected.  - &#x60;amount&#x3D;{Amount}&#x60;, where &#x60;{Amount}&#x60; is the transaction amount that will be withdrawn from the Payer’s account. &#x60;{Amount}&#x60; must be expressed in the form of the data type &#x60;Amount&#x60;.  - &#x60;currency&#x3D;{Currency}&#x60;, where &#x60;{Currency}&#x60; is the transaction currency for the amount that will be withdrawn from the Payer’s account. The &#x60;{Currency}&#x60; value must be expressed in the form of the enumeration &#x60;CurrencyCode&#x60;.  The following is an example URI containing all the required key-value pairs in the query string*:*  &#x60;GET /authorization/3d492671-b7af-4f3f-88de-76169b1bdf88?authenticationType&#x3D;OTP&amp;retriesLeft&#x3D;2&amp;amount&#x3D;102&amp;currency&#x3D;USD&#x60;
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use. (required)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public void authorizationsByIDGet(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull String accept, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod) throws ApiException {
        authorizationsByIDGetWithHttpInfo(ID, contentType, date, fsPIOPSource, accept, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod);
    }

    /**
     * Perform authorization
     * The HTTP request &#x60;GET /authorizations/{ID}&#x60; is used to request the Payer to enter the applicable credentials in the Payee FSP system. The &#x60;{ID}&#x60; in the URI should contain the &#x60;transactionRequestID&#x60;, received from the &#x60;POST /transactionRequests&#x60; service earlier in the process. This request requires a query string to be included in the URI, with the following key-value pairs*:*  - &#x60;authenticationType&#x3D;{Type}&#x60;, where &#x60;{Type}&#x60; value is a valid authentication type from the enumeration &#x60;AuthenticationType&#x60;.  - &#x60;retriesLeft&#x3D;&#x3D;{NrOfRetries}&#x60;, where &#x60;{NrOfRetries}&#x60; is the number of retries left before the financial transaction is rejected. &#x60;{NrOfRetries}&#x60; must be expressed in the form of the data type &#x60;Integer&#x60;. &#x60;retriesLeft&#x3D;1&#x60; means that this is the last retry before the financial transaction is rejected.  - &#x60;amount&#x3D;{Amount}&#x60;, where &#x60;{Amount}&#x60; is the transaction amount that will be withdrawn from the Payer’s account. &#x60;{Amount}&#x60; must be expressed in the form of the data type &#x60;Amount&#x60;.  - &#x60;currency&#x3D;{Currency}&#x60;, where &#x60;{Currency}&#x60; is the transaction currency for the amount that will be withdrawn from the Payer’s account. The &#x60;{Currency}&#x60; value must be expressed in the form of the enumeration &#x60;CurrencyCode&#x60;.  The following is an example URI containing all the required key-value pairs in the query string*:*  &#x60;GET /authorization/3d492671-b7af-4f3f-88de-76169b1bdf88?authenticationType&#x3D;OTP&amp;retriesLeft&#x3D;2&amp;amount&#x3D;102&amp;currency&#x3D;USD&#x60;
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use. (required)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<Void> authorizationsByIDGetWithHttpInfo(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull String accept, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod) throws ApiException {
        okhttp3.Call localVarCall = authorizationsByIDGetValidateBeforeCall(ID, contentType, date, fsPIOPSource, accept, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Perform authorization (asynchronously)
     * The HTTP request &#x60;GET /authorizations/{ID}&#x60; is used to request the Payer to enter the applicable credentials in the Payee FSP system. The &#x60;{ID}&#x60; in the URI should contain the &#x60;transactionRequestID&#x60;, received from the &#x60;POST /transactionRequests&#x60; service earlier in the process. This request requires a query string to be included in the URI, with the following key-value pairs*:*  - &#x60;authenticationType&#x3D;{Type}&#x60;, where &#x60;{Type}&#x60; value is a valid authentication type from the enumeration &#x60;AuthenticationType&#x60;.  - &#x60;retriesLeft&#x3D;&#x3D;{NrOfRetries}&#x60;, where &#x60;{NrOfRetries}&#x60; is the number of retries left before the financial transaction is rejected. &#x60;{NrOfRetries}&#x60; must be expressed in the form of the data type &#x60;Integer&#x60;. &#x60;retriesLeft&#x3D;1&#x60; means that this is the last retry before the financial transaction is rejected.  - &#x60;amount&#x3D;{Amount}&#x60;, where &#x60;{Amount}&#x60; is the transaction amount that will be withdrawn from the Payer’s account. &#x60;{Amount}&#x60; must be expressed in the form of the data type &#x60;Amount&#x60;.  - &#x60;currency&#x3D;{Currency}&#x60;, where &#x60;{Currency}&#x60; is the transaction currency for the amount that will be withdrawn from the Payer’s account. The &#x60;{Currency}&#x60; value must be expressed in the form of the enumeration &#x60;CurrencyCode&#x60;.  The following is an example URI containing all the required key-value pairs in the query string*:*  &#x60;GET /authorization/3d492671-b7af-4f3f-88de-76169b1bdf88?authenticationType&#x3D;OTP&amp;retriesLeft&#x3D;2&amp;amount&#x3D;102&amp;currency&#x3D;USD&#x60;
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param accept The &#x60;Accept&#x60; header field indicates the version of the API the client would like the server to use. (required)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 202 </td><td> Accepted </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call authorizationsByIDGetAsync(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull String accept, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = authorizationsByIDGetValidateBeforeCall(ID, contentType, date, fsPIOPSource, accept, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
    /**
     * Build call for authorizationsByIDPut
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param authorizationsIDPutResponse Authorization result returned. (required)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param contentLength The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes). (optional)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call authorizationsByIDPutCall(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull AuthorizationsIDPutResponse authorizationsIDPutResponse, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, @javax.annotation.Nullable Integer contentLength, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = authorizationsIDPutResponse;

        // create path and map variables
        String localVarPath = "/authorizations/{ID}"
            .replace("{" + "ID" + "}", localVarApiClient.escapeString(ID.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (contentType != null) {
            localVarHeaderParams.put("Content-Type", localVarApiClient.parameterToString(contentType));
        }


        if (date != null) {
            localVarHeaderParams.put("Date", localVarApiClient.parameterToString(date));
        }


        if (xForwardedFor != null) {
            localVarHeaderParams.put("X-Forwarded-For", localVarApiClient.parameterToString(xForwardedFor));
        }


        if (fsPIOPSource != null) {
            localVarHeaderParams.put("FSPIOP-Source", localVarApiClient.parameterToString(fsPIOPSource));
        }


        if (fsPIOPDestination != null) {
            localVarHeaderParams.put("FSPIOP-Destination", localVarApiClient.parameterToString(fsPIOPDestination));
        }


        if (fsPIOPEncryption != null) {
            localVarHeaderParams.put("FSPIOP-Encryption", localVarApiClient.parameterToString(fsPIOPEncryption));
        }


        if (fsPIOPSignature != null) {
            localVarHeaderParams.put("FSPIOP-Signature", localVarApiClient.parameterToString(fsPIOPSignature));
        }


        if (FSPIOP_URI != null) {
            localVarHeaderParams.put("FSPIOP-URI", localVarApiClient.parameterToString(FSPIOP_URI));
        }


        if (fsPIOPHTTPMethod != null) {
            localVarHeaderParams.put("FSPIOP-HTTP-Method", localVarApiClient.parameterToString(fsPIOPHTTPMethod));
        }


        if (contentLength != null) {
            localVarHeaderParams.put("Content-Length", localVarApiClient.parameterToString(contentLength));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "PUT", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call authorizationsByIDPutValidateBeforeCall(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull AuthorizationsIDPutResponse authorizationsIDPutResponse, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, @javax.annotation.Nullable Integer contentLength, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ID' is set
        if (ID == null) {
            throw new ApiException("Missing the required parameter 'ID' when calling authorizationsByIDPut(Async)");
        }

        // verify the required parameter 'contentType' is set
        if (contentType == null) {
            throw new ApiException("Missing the required parameter 'contentType' when calling authorizationsByIDPut(Async)");
        }

        // verify the required parameter 'date' is set
        if (date == null) {
            throw new ApiException("Missing the required parameter 'date' when calling authorizationsByIDPut(Async)");
        }

        // verify the required parameter 'fsPIOPSource' is set
        if (fsPIOPSource == null) {
            throw new ApiException("Missing the required parameter 'fsPIOPSource' when calling authorizationsByIDPut(Async)");
        }

        // verify the required parameter 'authorizationsIDPutResponse' is set
        if (authorizationsIDPutResponse == null) {
            throw new ApiException("Missing the required parameter 'authorizationsIDPutResponse' when calling authorizationsByIDPut(Async)");
        }

        return authorizationsByIDPutCall(ID, contentType, date, fsPIOPSource, authorizationsIDPutResponse, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, contentLength, _callback);

    }

    /**
     * Return authorization result
     * The callback &#x60;PUT /authorizations/{ID}&#x60; is used to inform the client of the result of a previously-requested authorization. The &#x60;{ID}&#x60; in the URI should contain the &#x60;{ID}&#x60; that was used in the &#x60;GET /authorizations/{ID}&#x60; request.
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param authorizationsIDPutResponse Authorization result returned. (required)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param contentLength The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes). (optional)
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public void authorizationsByIDPut(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull AuthorizationsIDPutResponse authorizationsIDPutResponse, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, @javax.annotation.Nullable Integer contentLength) throws ApiException {
        authorizationsByIDPutWithHttpInfo(ID, contentType, date, fsPIOPSource, authorizationsIDPutResponse, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, contentLength);
    }

    /**
     * Return authorization result
     * The callback &#x60;PUT /authorizations/{ID}&#x60; is used to inform the client of the result of a previously-requested authorization. The &#x60;{ID}&#x60; in the URI should contain the &#x60;{ID}&#x60; that was used in the &#x60;GET /authorizations/{ID}&#x60; request.
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param authorizationsIDPutResponse Authorization result returned. (required)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param contentLength The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes). (optional)
     * @return ApiResponse&lt;Void&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public ApiResponse<Void> authorizationsByIDPutWithHttpInfo(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull AuthorizationsIDPutResponse authorizationsIDPutResponse, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, @javax.annotation.Nullable Integer contentLength) throws ApiException {
        okhttp3.Call localVarCall = authorizationsByIDPutValidateBeforeCall(ID, contentType, date, fsPIOPSource, authorizationsIDPutResponse, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, contentLength, null);
        return localVarApiClient.execute(localVarCall);
    }

    /**
     * Return authorization result (asynchronously)
     * The callback &#x60;PUT /authorizations/{ID}&#x60; is used to inform the client of the result of a previously-requested authorization. The &#x60;{ID}&#x60; in the URI should contain the &#x60;{ID}&#x60; that was used in the &#x60;GET /authorizations/{ID}&#x60; request.
     * @param ID The identifier value. (required)
     * @param contentType The &#x60;Content-Type&#x60; header indicates the specific version of the API used to send the payload body. (required)
     * @param date The &#x60;Date&#x60; header field indicates the date when the request was sent. (required)
     * @param fsPIOPSource The &#x60;FSPIOP-Source&#x60; header field is a non-HTTP standard field used by the API for identifying the sender of the HTTP request. The field should be set by the original sender of the request. Required for routing and signature verification (see header field &#x60;FSPIOP-Signature&#x60;). (required)
     * @param authorizationsIDPutResponse Authorization result returned. (required)
     * @param xForwardedFor The &#x60;X-Forwarded-For&#x60; header field is an unofficially accepted standard used for informational purposes of the originating client IP address, as a request might pass multiple proxies, firewalls, and so on. Multiple &#x60;X-Forwarded-For&#x60; values should be expected and supported by implementers of the API.  **Note:** An alternative to &#x60;X-Forwarded-For&#x60; is defined in [RFC 7239](https://tools.ietf.org/html/rfc7239). However, to this point RFC 7239 is less-used and supported than &#x60;X-Forwarded-For&#x60;. (optional)
     * @param fsPIOPDestination The &#x60;FSPIOP-Destination&#x60; header field is a non-HTTP standard field used by the API for HTTP header based routing of requests and responses to the destination. The field must be set by the original sender of the request if the destination is known (valid for all services except GET /parties) so that any entities between the client and the server do not need to parse the payload for routing purposes. If the destination is not known (valid for service GET /parties), the field should be left empty. (optional)
     * @param fsPIOPEncryption The &#x60;FSPIOP-Encryption&#x60; header field is a non-HTTP standard field used by the API for applying end-to-end encryption of the request. (optional)
     * @param fsPIOPSignature The &#x60;FSPIOP-Signature&#x60; header field is a non-HTTP standard field used by the API for applying an end-to-end request signature. (optional)
     * @param FSPIOP_URI The &#x60;FSPIOP-URI&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service URI. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param fsPIOPHTTPMethod The &#x60;FSPIOP-HTTP-Method&#x60; header field is a non-HTTP standard field used by the API for signature verification, should contain the service HTTP method. Required if signature verification is used, for more information, see [the API Signature document](https://github.com/mojaloop/docs/tree/main/Specification%20Document%20Set). (optional)
     * @param contentLength The &#x60;Content-Length&#x60; header field indicates the anticipated size of the payload body. Only sent if there is a body.  **Note:** The API supports a maximum size of 5242880 bytes (5 Megabytes). (optional)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> OK </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 401 </td><td> Unauthorized </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 403 </td><td> Forbidden </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 404 </td><td> Not Found </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 405 </td><td> Method Not Allowed </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 406 </td><td> Not Acceptable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 501 </td><td> Not Implemented </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
        <tr><td> 503 </td><td> Service Unavailable </td><td>  * Content-Length -  <br>  * Content-Type -  <br>  </td></tr>
     </table>
     */
    public okhttp3.Call authorizationsByIDPutAsync(@javax.annotation.Nonnull String ID, @javax.annotation.Nonnull String contentType, @javax.annotation.Nonnull String date, @javax.annotation.Nonnull String fsPIOPSource, @javax.annotation.Nonnull AuthorizationsIDPutResponse authorizationsIDPutResponse, @javax.annotation.Nullable String xForwardedFor, @javax.annotation.Nullable String fsPIOPDestination, @javax.annotation.Nullable String fsPIOPEncryption, @javax.annotation.Nullable String fsPIOPSignature, @javax.annotation.Nullable String FSPIOP_URI, @javax.annotation.Nullable String fsPIOPHTTPMethod, @javax.annotation.Nullable Integer contentLength, final ApiCallback<Void> _callback) throws ApiException {

        okhttp3.Call localVarCall = authorizationsByIDPutValidateBeforeCall(ID, contentType, date, fsPIOPSource, authorizationsIDPutResponse, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, contentLength, _callback);
        localVarApiClient.executeAsync(localVarCall, _callback);
        return localVarCall;
    }
}
