/*
 * Copyright (c) 2026 ThitsaWorks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ExtensionList;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.IndividualQuoteResult;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * The object sent in the PUT /bulkQuotes/{ID} callback.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class BulkQuotesIDPutResponse {
  public static final String SERIALIZED_NAME_INDIVIDUAL_QUOTE_RESULTS = "individualQuoteResults";
  @SerializedName(SERIALIZED_NAME_INDIVIDUAL_QUOTE_RESULTS)
  @javax.annotation.Nullable
  private List<IndividualQuoteResult> individualQuoteResults = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXPIRATION = "expiration";
  @SerializedName(SERIALIZED_NAME_EXPIRATION)
  @javax.annotation.Nonnull
  private String expiration;

  public static final String SERIALIZED_NAME_EXTENSION_LIST = "extensionList";
  @SerializedName(SERIALIZED_NAME_EXTENSION_LIST)
  @javax.annotation.Nullable
  private ExtensionList extensionList;

  public BulkQuotesIDPutResponse() {
  }

  public BulkQuotesIDPutResponse individualQuoteResults(@javax.annotation.Nullable List<IndividualQuoteResult> individualQuoteResults) {
    this.individualQuoteResults = individualQuoteResults;
    return this;
  }

  public BulkQuotesIDPutResponse addIndividualQuoteResultsItem(IndividualQuoteResult individualQuoteResultsItem) {
    if (this.individualQuoteResults == null) {
      this.individualQuoteResults = new ArrayList<>();
    }
    this.individualQuoteResults.add(individualQuoteResultsItem);
    return this;
  }

  /**
   * Fees for each individual transaction, if any of them are charged per transaction.
   * @return individualQuoteResults
   */
  @javax.annotation.Nullable
  public List<IndividualQuoteResult> getIndividualQuoteResults() {
    return individualQuoteResults;
  }

  public void setIndividualQuoteResults(@javax.annotation.Nullable List<IndividualQuoteResult> individualQuoteResults) {
    this.individualQuoteResults = individualQuoteResults;
  }


  public BulkQuotesIDPutResponse expiration(@javax.annotation.Nonnull String expiration) {
    this.expiration = expiration;
    return this;
  }

  /**
   * The API data type DateTime is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons. The format is according to [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html), expressed in a combined date, time and time zone format. A more readable version of the format is yyyy-MM-ddTHH:mm:ss.SSS[-HH:MM]. Examples are \&quot;2016-05-24T08:38:08.699-04:00\&quot;, \&quot;2016-05-24T08:38:08.699Z\&quot; (where Z indicates Zulu time zone, same as UTC).
   * @return expiration
   */
  @javax.annotation.Nonnull
  public String getExpiration() {
    return expiration;
  }

  public void setExpiration(@javax.annotation.Nonnull String expiration) {
    this.expiration = expiration;
  }


  public BulkQuotesIDPutResponse extensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

  /**
   * Get extensionList
   * @return extensionList
   */
  @javax.annotation.Nullable
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkQuotesIDPutResponse bulkQuotesIDPutResponse = (BulkQuotesIDPutResponse) o;
    return Objects.equals(this.individualQuoteResults, bulkQuotesIDPutResponse.individualQuoteResults) &&
        Objects.equals(this.expiration, bulkQuotesIDPutResponse.expiration) &&
        Objects.equals(this.extensionList, bulkQuotesIDPutResponse.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(individualQuoteResults, expiration, extensionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkQuotesIDPutResponse {\n");
    sb.append("    individualQuoteResults: ").append(toIndentedString(individualQuoteResults)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("individualQuoteResults", "expiration", "extensionList"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("expiration"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BulkQuotesIDPutResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BulkQuotesIDPutResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BulkQuotesIDPutResponse is not found in the empty JSON string", BulkQuotesIDPutResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BulkQuotesIDPutResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BulkQuotesIDPutResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BulkQuotesIDPutResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("individualQuoteResults") != null && !jsonObj.get("individualQuoteResults").isJsonNull()) {
        JsonArray jsonArrayindividualQuoteResults = jsonObj.getAsJsonArray("individualQuoteResults");
        if (jsonArrayindividualQuoteResults != null) {
          // ensure the json data is an array
          if (!jsonObj.get("individualQuoteResults").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `individualQuoteResults` to be an array in the JSON string but got `%s`", jsonObj.get("individualQuoteResults").toString()));
          }

          // validate the optional field `individualQuoteResults` (array)
          for (int i = 0; i < jsonArrayindividualQuoteResults.size(); i++) {
            IndividualQuoteResult.validateJsonElement(jsonArrayindividualQuoteResults.get(i));
          };
        }
      }
      if (!jsonObj.get("expiration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `expiration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiration").toString()));
      }
      // validate the optional field `extensionList`
      if (jsonObj.get("extensionList") != null && !jsonObj.get("extensionList").isJsonNull()) {
        ExtensionList.validateJsonElement(jsonObj.get("extensionList"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BulkQuotesIDPutResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BulkQuotesIDPutResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BulkQuotesIDPutResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BulkQuotesIDPutResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<BulkQuotesIDPutResponse>() {
           @Override
           public void write(JsonWriter out, BulkQuotesIDPutResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BulkQuotesIDPutResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BulkQuotesIDPutResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BulkQuotesIDPutResponse
   * @throws IOException if the JSON string is invalid with respect to BulkQuotesIDPutResponse
   */
  public static BulkQuotesIDPutResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BulkQuotesIDPutResponse.class);
  }

  /**
   * Convert an instance of BulkQuotesIDPutResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

