/*
 * Copyright (c) 2026 ThitsaWorks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Below are the allowed values for the enumeration. - RECEIVED - Payee FSP has received the bulk transfer from the Payer FSP. - PENDING - Payee FSP has validated the bulk transfer. - ACCEPTED - Payee FSP has accepted to process the bulk transfer. - PROCESSING - Payee FSP has started to transfer fund to the Payees. - COMPLETED - Payee FSP has completed transfer of funds to the Payees. - REJECTED - Payee FSP has rejected to process the bulk transfer.
 */
@JsonAdapter(BulkTransferState.Adapter.class)
public enum BulkTransferState {
  
  RECEIVED("RECEIVED"),
  
  PENDING("PENDING"),
  
  ACCEPTED("ACCEPTED"),
  
  PROCESSING("PROCESSING"),
  
  COMPLETED("COMPLETED"),
  
  REJECTED("REJECTED");

  private String value;

  BulkTransferState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static BulkTransferState fromValue(String value) {
    for (BulkTransferState b : BulkTransferState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<BulkTransferState> {
    @Override
    public void write(final JsonWriter jsonWriter, final BulkTransferState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public BulkTransferState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return BulkTransferState.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    BulkTransferState.fromValue(value);
  }
}

