/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ExtensionList;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.IndividualTransfer;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * The object sent in the POST /bulkTransfers request.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class BulkTransfersPostRequest {
  public static final String SERIALIZED_NAME_BULK_TRANSFER_ID = "bulkTransferId";
  @SerializedName(SERIALIZED_NAME_BULK_TRANSFER_ID)
  @javax.annotation.Nonnull
  private String bulkTransferId;

  public static final String SERIALIZED_NAME_BULK_QUOTE_ID = "bulkQuoteId";
  @SerializedName(SERIALIZED_NAME_BULK_QUOTE_ID)
  @javax.annotation.Nonnull
  private String bulkQuoteId;

  public static final String SERIALIZED_NAME_PAYER_FSP = "payerFsp";
  @SerializedName(SERIALIZED_NAME_PAYER_FSP)
  @javax.annotation.Nonnull
  private String payerFsp;

  public static final String SERIALIZED_NAME_PAYEE_FSP = "payeeFsp";
  @SerializedName(SERIALIZED_NAME_PAYEE_FSP)
  @javax.annotation.Nonnull
  private String payeeFsp;

  public static final String SERIALIZED_NAME_INDIVIDUAL_TRANSFERS = "individualTransfers";
  @SerializedName(SERIALIZED_NAME_INDIVIDUAL_TRANSFERS)
  @javax.annotation.Nonnull
  private List<IndividualTransfer> individualTransfers = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXPIRATION = "expiration";
  @SerializedName(SERIALIZED_NAME_EXPIRATION)
  @javax.annotation.Nonnull
  private String expiration;

  public static final String SERIALIZED_NAME_EXTENSION_LIST = "extensionList";
  @SerializedName(SERIALIZED_NAME_EXTENSION_LIST)
  @javax.annotation.Nullable
  private ExtensionList extensionList;

  public BulkTransfersPostRequest() {
  }

  public BulkTransfersPostRequest bulkTransferId(@javax.annotation.Nonnull String bulkTransferId) {
    this.bulkTransferId = bulkTransferId;
    return this;
  }

  /**
   * Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to [RFC 4122](https://tools.ietf.org/html/rfc4122), that is restricted by a regular expression for interoperability reasons. A UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
   * @return bulkTransferId
   */
  @javax.annotation.Nonnull
  public String getBulkTransferId() {
    return bulkTransferId;
  }

  public void setBulkTransferId(@javax.annotation.Nonnull String bulkTransferId) {
    this.bulkTransferId = bulkTransferId;
  }


  public BulkTransfersPostRequest bulkQuoteId(@javax.annotation.Nonnull String bulkQuoteId) {
    this.bulkQuoteId = bulkQuoteId;
    return this;
  }

  /**
   * Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to [RFC 4122](https://tools.ietf.org/html/rfc4122), that is restricted by a regular expression for interoperability reasons. A UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
   * @return bulkQuoteId
   */
  @javax.annotation.Nonnull
  public String getBulkQuoteId() {
    return bulkQuoteId;
  }

  public void setBulkQuoteId(@javax.annotation.Nonnull String bulkQuoteId) {
    this.bulkQuoteId = bulkQuoteId;
  }


  public BulkTransfersPostRequest payerFsp(@javax.annotation.Nonnull String payerFsp) {
    this.payerFsp = payerFsp;
    return this;
  }

  /**
   * FSP identifier.
   * @return payerFsp
   */
  @javax.annotation.Nonnull
  public String getPayerFsp() {
    return payerFsp;
  }

  public void setPayerFsp(@javax.annotation.Nonnull String payerFsp) {
    this.payerFsp = payerFsp;
  }


  public BulkTransfersPostRequest payeeFsp(@javax.annotation.Nonnull String payeeFsp) {
    this.payeeFsp = payeeFsp;
    return this;
  }

  /**
   * FSP identifier.
   * @return payeeFsp
   */
  @javax.annotation.Nonnull
  public String getPayeeFsp() {
    return payeeFsp;
  }

  public void setPayeeFsp(@javax.annotation.Nonnull String payeeFsp) {
    this.payeeFsp = payeeFsp;
  }


  public BulkTransfersPostRequest individualTransfers(@javax.annotation.Nonnull List<IndividualTransfer> individualTransfers) {
    this.individualTransfers = individualTransfers;
    return this;
  }

  public BulkTransfersPostRequest addIndividualTransfersItem(IndividualTransfer individualTransfersItem) {
    if (this.individualTransfers == null) {
      this.individualTransfers = new ArrayList<>();
    }
    this.individualTransfers.add(individualTransfersItem);
    return this;
  }

  /**
   * List of IndividualTransfer elements.
   * @return individualTransfers
   */
  @javax.annotation.Nonnull
  public List<IndividualTransfer> getIndividualTransfers() {
    return individualTransfers;
  }

  public void setIndividualTransfers(@javax.annotation.Nonnull List<IndividualTransfer> individualTransfers) {
    this.individualTransfers = individualTransfers;
  }


  public BulkTransfersPostRequest expiration(@javax.annotation.Nonnull String expiration) {
    this.expiration = expiration;
    return this;
  }

  /**
   * The API data type DateTime is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons. The format is according to [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html), expressed in a combined date, time and time zone format. A more readable version of the format is yyyy-MM-ddTHH:mm:ss.SSS[-HH:MM]. Examples are \&quot;2016-05-24T08:38:08.699-04:00\&quot;, \&quot;2016-05-24T08:38:08.699Z\&quot; (where Z indicates Zulu time zone, same as UTC).
   * @return expiration
   */
  @javax.annotation.Nonnull
  public String getExpiration() {
    return expiration;
  }

  public void setExpiration(@javax.annotation.Nonnull String expiration) {
    this.expiration = expiration;
  }


  public BulkTransfersPostRequest extensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

  /**
   * Get extensionList
   * @return extensionList
   */
  @javax.annotation.Nullable
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkTransfersPostRequest bulkTransfersPostRequest = (BulkTransfersPostRequest) o;
    return Objects.equals(this.bulkTransferId, bulkTransfersPostRequest.bulkTransferId) &&
        Objects.equals(this.bulkQuoteId, bulkTransfersPostRequest.bulkQuoteId) &&
        Objects.equals(this.payerFsp, bulkTransfersPostRequest.payerFsp) &&
        Objects.equals(this.payeeFsp, bulkTransfersPostRequest.payeeFsp) &&
        Objects.equals(this.individualTransfers, bulkTransfersPostRequest.individualTransfers) &&
        Objects.equals(this.expiration, bulkTransfersPostRequest.expiration) &&
        Objects.equals(this.extensionList, bulkTransfersPostRequest.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bulkTransferId, bulkQuoteId, payerFsp, payeeFsp, individualTransfers, expiration, extensionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkTransfersPostRequest {\n");
    sb.append("    bulkTransferId: ").append(toIndentedString(bulkTransferId)).append("\n");
    sb.append("    bulkQuoteId: ").append(toIndentedString(bulkQuoteId)).append("\n");
    sb.append("    payerFsp: ").append(toIndentedString(payerFsp)).append("\n");
    sb.append("    payeeFsp: ").append(toIndentedString(payeeFsp)).append("\n");
    sb.append("    individualTransfers: ").append(toIndentedString(individualTransfers)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("bulkTransferId", "bulkQuoteId", "payerFsp", "payeeFsp", "individualTransfers", "expiration", "extensionList"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("bulkTransferId", "bulkQuoteId", "payerFsp", "payeeFsp", "individualTransfers", "expiration"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BulkTransfersPostRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BulkTransfersPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in BulkTransfersPostRequest is not found in the empty JSON string", BulkTransfersPostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BulkTransfersPostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `BulkTransfersPostRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : BulkTransfersPostRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("bulkTransferId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `bulkTransferId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bulkTransferId").toString()));
      }
      if (!jsonObj.get("bulkQuoteId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `bulkQuoteId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bulkQuoteId").toString()));
      }
      if (!jsonObj.get("payerFsp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payerFsp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payerFsp").toString()));
      }
      if (!jsonObj.get("payeeFsp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payeeFsp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payeeFsp").toString()));
      }
      if (jsonObj.get("individualTransfers") != null) {
        if (!jsonObj.get("individualTransfers").isJsonArray()) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `individualTransfers` to be an array in the JSON string but got `%s`", jsonObj.get("individualTransfers").toString()));
        }
        JsonArray jsonArrayindividualTransfers = jsonObj.getAsJsonArray("individualTransfers");
        // validate the required field `individualTransfers` (array)
        for (int i = 0; i < jsonArrayindividualTransfers.size(); i++) {
          IndividualTransfer.validateJsonElement(jsonArrayindividualTransfers.get(i));
        }
      }
      if (!jsonObj.get("expiration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `expiration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiration").toString()));
      }
      // validate the optional field `extensionList`
      if (jsonObj.get("extensionList") != null && !jsonObj.get("extensionList").isJsonNull()) {
        ExtensionList.validateJsonElement(jsonObj.get("extensionList"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BulkTransfersPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BulkTransfersPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BulkTransfersPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BulkTransfersPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<BulkTransfersPostRequest>() {
           @Override
           public void write(JsonWriter out, BulkTransfersPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BulkTransfersPostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BulkTransfersPostRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BulkTransfersPostRequest
   * @throws IOException if the JSON string is invalid with respect to BulkTransfersPostRequest
   */
  public static BulkTransfersPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BulkTransfersPostRequest.class);
  }

  /**
   * Convert an instance of BulkTransfersPostRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

