/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.AmountType;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ExtensionList;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxCharge;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxMoney;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * A DFSP will be able to request a currency conversion, and an FX provider will be able to describe its involvement in a proposed transfer, using a FxConversion object.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class FxConversion {
  public static final String SERIALIZED_NAME_CONVERSION_ID = "conversionId";
  @SerializedName(SERIALIZED_NAME_CONVERSION_ID)
  @javax.annotation.Nonnull
  private String conversionId;

  public static final String SERIALIZED_NAME_DETERMINING_TRANSFER_ID = "determiningTransferId";
  @SerializedName(SERIALIZED_NAME_DETERMINING_TRANSFER_ID)
  @javax.annotation.Nullable
  private String determiningTransferId;

  public static final String SERIALIZED_NAME_INITIATING_FSP = "initiatingFsp";
  @SerializedName(SERIALIZED_NAME_INITIATING_FSP)
  @javax.annotation.Nonnull
  private String initiatingFsp;

  public static final String SERIALIZED_NAME_COUNTER_PARTY_FSP = "counterPartyFsp";
  @SerializedName(SERIALIZED_NAME_COUNTER_PARTY_FSP)
  @javax.annotation.Nonnull
  private String counterPartyFsp;

  public static final String SERIALIZED_NAME_AMOUNT_TYPE = "amountType";
  @SerializedName(SERIALIZED_NAME_AMOUNT_TYPE)
  @javax.annotation.Nonnull
  private AmountType amountType;

  public static final String SERIALIZED_NAME_SOURCE_AMOUNT = "sourceAmount";
  @SerializedName(SERIALIZED_NAME_SOURCE_AMOUNT)
  @javax.annotation.Nonnull
  private FxMoney sourceAmount;

  public static final String SERIALIZED_NAME_TARGET_AMOUNT = "targetAmount";
  @SerializedName(SERIALIZED_NAME_TARGET_AMOUNT)
  @javax.annotation.Nonnull
  private FxMoney targetAmount;

  public static final String SERIALIZED_NAME_EXPIRATION = "expiration";
  @SerializedName(SERIALIZED_NAME_EXPIRATION)
  @javax.annotation.Nonnull
  private String expiration;

  public static final String SERIALIZED_NAME_CHARGES = "charges";
  @SerializedName(SERIALIZED_NAME_CHARGES)
  @javax.annotation.Nullable
  private List<FxCharge> charges = new ArrayList<>();

  public static final String SERIALIZED_NAME_EXTENSION_LIST = "extensionList";
  @SerializedName(SERIALIZED_NAME_EXTENSION_LIST)
  @javax.annotation.Nullable
  private ExtensionList extensionList;

  public FxConversion() {
  }

  public FxConversion conversionId(@javax.annotation.Nonnull String conversionId) {
    this.conversionId = conversionId;
    return this;
  }

  /**
   * An end-to-end identifier for the conversion request.
   * @return conversionId
   */
  @javax.annotation.Nonnull
  public String getConversionId() {
    return conversionId;
  }

  public void setConversionId(@javax.annotation.Nonnull String conversionId) {
    this.conversionId = conversionId;
  }


  public FxConversion determiningTransferId(@javax.annotation.Nullable String determiningTransferId) {
    this.determiningTransferId = determiningTransferId;
    return this;
  }

  /**
   * The transaction ID of the transfer on whose success this currency conversion depends.
   * @return determiningTransferId
   */
  @javax.annotation.Nullable
  public String getDeterminingTransferId() {
    return determiningTransferId;
  }

  public void setDeterminingTransferId(@javax.annotation.Nullable String determiningTransferId) {
    this.determiningTransferId = determiningTransferId;
  }


  public FxConversion initiatingFsp(@javax.annotation.Nonnull String initiatingFsp) {
    this.initiatingFsp = initiatingFsp;
    return this;
  }

  /**
   * The id of the participant who is requesting a currency conversion.
   * @return initiatingFsp
   */
  @javax.annotation.Nonnull
  public String getInitiatingFsp() {
    return initiatingFsp;
  }

  public void setInitiatingFsp(@javax.annotation.Nonnull String initiatingFsp) {
    this.initiatingFsp = initiatingFsp;
  }


  public FxConversion counterPartyFsp(@javax.annotation.Nonnull String counterPartyFsp) {
    this.counterPartyFsp = counterPartyFsp;
    return this;
  }

  /**
   * The ID of the FXP performing the conversion.
   * @return counterPartyFsp
   */
  @javax.annotation.Nonnull
  public String getCounterPartyFsp() {
    return counterPartyFsp;
  }

  public void setCounterPartyFsp(@javax.annotation.Nonnull String counterPartyFsp) {
    this.counterPartyFsp = counterPartyFsp;
  }


  public FxConversion amountType(@javax.annotation.Nonnull AmountType amountType) {
    this.amountType = amountType;
    return this;
  }

  /**
   * This is the AmountType for the base transaction - If SEND - then any charges levied by the FXP as part of the transaction will be deducted by the FXP from the amount shown for the target party in the conversion. If RECEIVE - then any charges levied by the FXP as part of the transaction will be added by the FXP to the amount shown for the source party in the conversion.
   * @return amountType
   */
  @javax.annotation.Nonnull
  public AmountType getAmountType() {
    return amountType;
  }

  public void setAmountType(@javax.annotation.Nonnull AmountType amountType) {
    this.amountType = amountType;
  }


  public FxConversion sourceAmount(@javax.annotation.Nonnull FxMoney sourceAmount) {
    this.sourceAmount = sourceAmount;
    return this;
  }

  /**
   * The amount to be converted, expressed in the source currency.
   * @return sourceAmount
   */
  @javax.annotation.Nonnull
  public FxMoney getSourceAmount() {
    return sourceAmount;
  }

  public void setSourceAmount(@javax.annotation.Nonnull FxMoney sourceAmount) {
    this.sourceAmount = sourceAmount;
  }


  public FxConversion targetAmount(@javax.annotation.Nonnull FxMoney targetAmount) {
    this.targetAmount = targetAmount;
    return this;
  }

  /**
   * The converted amount, expressed in the target currency.
   * @return targetAmount
   */
  @javax.annotation.Nonnull
  public FxMoney getTargetAmount() {
    return targetAmount;
  }

  public void setTargetAmount(@javax.annotation.Nonnull FxMoney targetAmount) {
    this.targetAmount = targetAmount;
  }


  public FxConversion expiration(@javax.annotation.Nonnull String expiration) {
    this.expiration = expiration;
    return this;
  }

  /**
   * The end of the period for which the currency conversion is required to remain valid.
   * @return expiration
   */
  @javax.annotation.Nonnull
  public String getExpiration() {
    return expiration;
  }

  public void setExpiration(@javax.annotation.Nonnull String expiration) {
    this.expiration = expiration;
  }


  public FxConversion charges(@javax.annotation.Nullable List<FxCharge> charges) {
    this.charges = charges;
    return this;
  }

  public FxConversion addChargesItem(FxCharge chargesItem) {
    if (this.charges == null) {
      this.charges = new ArrayList<>();
    }
    this.charges.add(chargesItem);
    return this;
  }

  /**
   * One or more charges which the FXP intends to levy as part of the currency conversion, or which the payee DFSP intends to add to the amount transferred.
   * @return charges
   */
  @javax.annotation.Nullable
  public List<FxCharge> getCharges() {
    return charges;
  }

  public void setCharges(@javax.annotation.Nullable List<FxCharge> charges) {
    this.charges = charges;
  }


  public FxConversion extensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

  /**
   * The extension list for the currency conversion request.
   * @return extensionList
   */
  @javax.annotation.Nullable
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FxConversion fxConversion = (FxConversion) o;
    return Objects.equals(this.conversionId, fxConversion.conversionId) &&
        Objects.equals(this.determiningTransferId, fxConversion.determiningTransferId) &&
        Objects.equals(this.initiatingFsp, fxConversion.initiatingFsp) &&
        Objects.equals(this.counterPartyFsp, fxConversion.counterPartyFsp) &&
        Objects.equals(this.amountType, fxConversion.amountType) &&
        Objects.equals(this.sourceAmount, fxConversion.sourceAmount) &&
        Objects.equals(this.targetAmount, fxConversion.targetAmount) &&
        Objects.equals(this.expiration, fxConversion.expiration) &&
        Objects.equals(this.charges, fxConversion.charges) &&
        Objects.equals(this.extensionList, fxConversion.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conversionId, determiningTransferId, initiatingFsp, counterPartyFsp, amountType, sourceAmount, targetAmount, expiration, charges, extensionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FxConversion {\n");
    sb.append("    conversionId: ").append(toIndentedString(conversionId)).append("\n");
    sb.append("    determiningTransferId: ").append(toIndentedString(determiningTransferId)).append("\n");
    sb.append("    initiatingFsp: ").append(toIndentedString(initiatingFsp)).append("\n");
    sb.append("    counterPartyFsp: ").append(toIndentedString(counterPartyFsp)).append("\n");
    sb.append("    amountType: ").append(toIndentedString(amountType)).append("\n");
    sb.append("    sourceAmount: ").append(toIndentedString(sourceAmount)).append("\n");
    sb.append("    targetAmount: ").append(toIndentedString(targetAmount)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    charges: ").append(toIndentedString(charges)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("conversionId", "determiningTransferId", "initiatingFsp", "counterPartyFsp", "amountType", "sourceAmount", "targetAmount", "expiration", "charges", "extensionList"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("conversionId", "initiatingFsp", "counterPartyFsp", "amountType", "sourceAmount", "targetAmount", "expiration"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FxConversion
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FxConversion.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in FxConversion is not found in the empty JSON string", FxConversion.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FxConversion.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FxConversion` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FxConversion.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("conversionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `conversionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("conversionId").toString()));
      }
      if ((jsonObj.get("determiningTransferId") != null && !jsonObj.get("determiningTransferId").isJsonNull()) && !jsonObj.get("determiningTransferId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `determiningTransferId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("determiningTransferId").toString()));
      }
      if (!jsonObj.get("initiatingFsp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `initiatingFsp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("initiatingFsp").toString()));
      }
      if (!jsonObj.get("counterPartyFsp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `counterPartyFsp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("counterPartyFsp").toString()));
      }
      // validate the required field `amountType`
      AmountType.validateJsonElement(jsonObj.get("amountType"));
      // validate the required field `sourceAmount`
      FxMoney.validateJsonElement(jsonObj.get("sourceAmount"));
      // validate the required field `targetAmount`
      FxMoney.validateJsonElement(jsonObj.get("targetAmount"));
      if (!jsonObj.get("expiration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `expiration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiration").toString()));
      }
      if (jsonObj.get("charges") != null && !jsonObj.get("charges").isJsonNull()) {
        JsonArray jsonArraycharges = jsonObj.getAsJsonArray("charges");
        if (jsonArraycharges != null) {
          // ensure the json data is an array
          if (!jsonObj.get("charges").isJsonArray()) {
            throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `charges` to be an array in the JSON string but got `%s`", jsonObj.get("charges").toString()));
          }

          // validate the optional field `charges` (array)
          for (int i = 0; i < jsonArraycharges.size(); i++) {
            FxCharge.validateJsonElement(jsonArraycharges.get(i));
          };
        }
      }
      // validate the optional field `extensionList`
      if (jsonObj.get("extensionList") != null && !jsonObj.get("extensionList").isJsonNull()) {
        ExtensionList.validateJsonElement(jsonObj.get("extensionList"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FxConversion.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FxConversion' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FxConversion> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FxConversion.class));

       return (TypeAdapter<T>) new TypeAdapter<FxConversion>() {
           @Override
           public void write(JsonWriter out, FxConversion value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FxConversion read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FxConversion given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FxConversion
   * @throws IOException if the JSON string is invalid with respect to FxConversion
   */
  public static FxConversion fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FxConversion.class);
  }

  /**
   * Convert an instance of FxConversion to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

