/*
 * Copyright (c) 2024-2026 ThitsaWorks Pte. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxConversion;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * The object sent in the POST /fxQuotes request.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class FxQuotesPostRequest {
  public static final String SERIALIZED_NAME_CONVERSION_REQUEST_ID = "conversionRequestId";
  @SerializedName(SERIALIZED_NAME_CONVERSION_REQUEST_ID)
  @javax.annotation.Nonnull
  private String conversionRequestId;

  public static final String SERIALIZED_NAME_CONVERSION_TERMS = "conversionTerms";
  @SerializedName(SERIALIZED_NAME_CONVERSION_TERMS)
  @javax.annotation.Nonnull
  private FxConversion conversionTerms;

  public FxQuotesPostRequest() {
  }

  public FxQuotesPostRequest conversionRequestId(@javax.annotation.Nonnull String conversionRequestId) {
    this.conversionRequestId = conversionRequestId;
    return this;
  }

  /**
   * An end-to-end identifier for the conversion quotation request.
   * @return conversionRequestId
   */
  @javax.annotation.Nonnull
  public String getConversionRequestId() {
    return conversionRequestId;
  }

  public void setConversionRequestId(@javax.annotation.Nonnull String conversionRequestId) {
    this.conversionRequestId = conversionRequestId;
  }


  public FxQuotesPostRequest conversionTerms(@javax.annotation.Nonnull FxConversion conversionTerms) {
    this.conversionTerms = conversionTerms;
    return this;
  }

  /**
   * The terms of the currency conversion for which a quotation is sought.
   * @return conversionTerms
   */
  @javax.annotation.Nonnull
  public FxConversion getConversionTerms() {
    return conversionTerms;
  }

  public void setConversionTerms(@javax.annotation.Nonnull FxConversion conversionTerms) {
    this.conversionTerms = conversionTerms;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FxQuotesPostRequest fxQuotesPostRequest = (FxQuotesPostRequest) o;
    return Objects.equals(this.conversionRequestId, fxQuotesPostRequest.conversionRequestId) &&
        Objects.equals(this.conversionTerms, fxQuotesPostRequest.conversionTerms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(conversionRequestId, conversionTerms);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FxQuotesPostRequest {\n");
    sb.append("    conversionRequestId: ").append(toIndentedString(conversionRequestId)).append("\n");
    sb.append("    conversionTerms: ").append(toIndentedString(conversionTerms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("conversionRequestId", "conversionTerms"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("conversionRequestId", "conversionTerms"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to FxQuotesPostRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FxQuotesPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in FxQuotesPostRequest is not found in the empty JSON string", FxQuotesPostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FxQuotesPostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `FxQuotesPostRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FxQuotesPostRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("conversionRequestId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `conversionRequestId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("conversionRequestId").toString()));
      }
      // validate the required field `conversionTerms`
      FxConversion.validateJsonElement(jsonObj.get("conversionTerms"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FxQuotesPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FxQuotesPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FxQuotesPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FxQuotesPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<FxQuotesPostRequest>() {
           @Override
           public void write(JsonWriter out, FxQuotesPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FxQuotesPostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of FxQuotesPostRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of FxQuotesPostRequest
   * @throws IOException if the JSON string is invalid with respect to FxQuotesPostRequest
   */
  public static FxQuotesPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FxQuotesPostRequest.class);
  }

  /**
   * Convert an instance of FxQuotesPostRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

