/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformation;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ExtensionList;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.Money;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.Party;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * Data model for the complex type IndividualQuoteResult.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class IndividualQuoteResult {
  public static final String SERIALIZED_NAME_QUOTE_ID = "quoteId";
  @SerializedName(SERIALIZED_NAME_QUOTE_ID)
  @javax.annotation.Nonnull
  private String quoteId;

  public static final String SERIALIZED_NAME_PAYEE = "payee";
  @SerializedName(SERIALIZED_NAME_PAYEE)
  @javax.annotation.Nullable
  private Party payee;

  public static final String SERIALIZED_NAME_TRANSFER_AMOUNT = "transferAmount";
  @SerializedName(SERIALIZED_NAME_TRANSFER_AMOUNT)
  @javax.annotation.Nullable
  private Money transferAmount;

  public static final String SERIALIZED_NAME_PAYEE_RECEIVE_AMOUNT = "payeeReceiveAmount";
  @SerializedName(SERIALIZED_NAME_PAYEE_RECEIVE_AMOUNT)
  @javax.annotation.Nullable
  private Money payeeReceiveAmount;

  public static final String SERIALIZED_NAME_PAYEE_FSP_FEE = "payeeFspFee";
  @SerializedName(SERIALIZED_NAME_PAYEE_FSP_FEE)
  @javax.annotation.Nullable
  private Money payeeFspFee;

  public static final String SERIALIZED_NAME_PAYEE_FSP_COMMISSION = "payeeFspCommission";
  @SerializedName(SERIALIZED_NAME_PAYEE_FSP_COMMISSION)
  @javax.annotation.Nullable
  private Money payeeFspCommission;

  public static final String SERIALIZED_NAME_ILP_PACKET = "ilpPacket";
  @SerializedName(SERIALIZED_NAME_ILP_PACKET)
  @javax.annotation.Nullable
  private String ilpPacket;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  @javax.annotation.Nullable
  private String condition;

  public static final String SERIALIZED_NAME_ERROR_INFORMATION = "errorInformation";
  @SerializedName(SERIALIZED_NAME_ERROR_INFORMATION)
  @javax.annotation.Nullable
  private ErrorInformation errorInformation;

  public static final String SERIALIZED_NAME_EXTENSION_LIST = "extensionList";
  @SerializedName(SERIALIZED_NAME_EXTENSION_LIST)
  @javax.annotation.Nullable
  private ExtensionList extensionList;

  public IndividualQuoteResult() {
  }

  public IndividualQuoteResult quoteId(@javax.annotation.Nonnull String quoteId) {
    this.quoteId = quoteId;
    return this;
  }

  /**
   * Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to [RFC 4122](https://tools.ietf.org/html/rfc4122), that is restricted by a regular expression for interoperability reasons. A UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
   * @return quoteId
   */
  @javax.annotation.Nonnull
  public String getQuoteId() {
    return quoteId;
  }

  public void setQuoteId(@javax.annotation.Nonnull String quoteId) {
    this.quoteId = quoteId;
  }


  public IndividualQuoteResult payee(@javax.annotation.Nullable Party payee) {
    this.payee = payee;
    return this;
  }

  /**
   * Get payee
   * @return payee
   */
  @javax.annotation.Nullable
  public Party getPayee() {
    return payee;
  }

  public void setPayee(@javax.annotation.Nullable Party payee) {
    this.payee = payee;
  }


  public IndividualQuoteResult transferAmount(@javax.annotation.Nullable Money transferAmount) {
    this.transferAmount = transferAmount;
    return this;
  }

  /**
   * Get transferAmount
   * @return transferAmount
   */
  @javax.annotation.Nullable
  public Money getTransferAmount() {
    return transferAmount;
  }

  public void setTransferAmount(@javax.annotation.Nullable Money transferAmount) {
    this.transferAmount = transferAmount;
  }


  public IndividualQuoteResult payeeReceiveAmount(@javax.annotation.Nullable Money payeeReceiveAmount) {
    this.payeeReceiveAmount = payeeReceiveAmount;
    return this;
  }

  /**
   * Get payeeReceiveAmount
   * @return payeeReceiveAmount
   */
  @javax.annotation.Nullable
  public Money getPayeeReceiveAmount() {
    return payeeReceiveAmount;
  }

  public void setPayeeReceiveAmount(@javax.annotation.Nullable Money payeeReceiveAmount) {
    this.payeeReceiveAmount = payeeReceiveAmount;
  }


  public IndividualQuoteResult payeeFspFee(@javax.annotation.Nullable Money payeeFspFee) {
    this.payeeFspFee = payeeFspFee;
    return this;
  }

  /**
   * Get payeeFspFee
   * @return payeeFspFee
   */
  @javax.annotation.Nullable
  public Money getPayeeFspFee() {
    return payeeFspFee;
  }

  public void setPayeeFspFee(@javax.annotation.Nullable Money payeeFspFee) {
    this.payeeFspFee = payeeFspFee;
  }


  public IndividualQuoteResult payeeFspCommission(@javax.annotation.Nullable Money payeeFspCommission) {
    this.payeeFspCommission = payeeFspCommission;
    return this;
  }

  /**
   * Get payeeFspCommission
   * @return payeeFspCommission
   */
  @javax.annotation.Nullable
  public Money getPayeeFspCommission() {
    return payeeFspCommission;
  }

  public void setPayeeFspCommission(@javax.annotation.Nullable Money payeeFspCommission) {
    this.payeeFspCommission = payeeFspCommission;
  }


  public IndividualQuoteResult ilpPacket(@javax.annotation.Nullable String ilpPacket) {
    this.ilpPacket = ilpPacket;
    return this;
  }

  /**
   * Information for recipient (transport layer information).
   * @return ilpPacket
   */
  @javax.annotation.Nullable
  public String getIlpPacket() {
    return ilpPacket;
  }

  public void setIlpPacket(@javax.annotation.Nullable String ilpPacket) {
    this.ilpPacket = ilpPacket;
  }


  public IndividualQuoteResult condition(@javax.annotation.Nullable String condition) {
    this.condition = condition;
    return this;
  }

  /**
   * Condition that must be attached to the transfer by the Payer.
   * @return condition
   */
  @javax.annotation.Nullable
  public String getCondition() {
    return condition;
  }

  public void setCondition(@javax.annotation.Nullable String condition) {
    this.condition = condition;
  }


  public IndividualQuoteResult errorInformation(@javax.annotation.Nullable ErrorInformation errorInformation) {
    this.errorInformation = errorInformation;
    return this;
  }

  /**
   * Get errorInformation
   * @return errorInformation
   */
  @javax.annotation.Nullable
  public ErrorInformation getErrorInformation() {
    return errorInformation;
  }

  public void setErrorInformation(@javax.annotation.Nullable ErrorInformation errorInformation) {
    this.errorInformation = errorInformation;
  }


  public IndividualQuoteResult extensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

  /**
   * Get extensionList
   * @return extensionList
   */
  @javax.annotation.Nullable
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndividualQuoteResult individualQuoteResult = (IndividualQuoteResult) o;
    return Objects.equals(this.quoteId, individualQuoteResult.quoteId) &&
        Objects.equals(this.payee, individualQuoteResult.payee) &&
        Objects.equals(this.transferAmount, individualQuoteResult.transferAmount) &&
        Objects.equals(this.payeeReceiveAmount, individualQuoteResult.payeeReceiveAmount) &&
        Objects.equals(this.payeeFspFee, individualQuoteResult.payeeFspFee) &&
        Objects.equals(this.payeeFspCommission, individualQuoteResult.payeeFspCommission) &&
        Objects.equals(this.ilpPacket, individualQuoteResult.ilpPacket) &&
        Objects.equals(this.condition, individualQuoteResult.condition) &&
        Objects.equals(this.errorInformation, individualQuoteResult.errorInformation) &&
        Objects.equals(this.extensionList, individualQuoteResult.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quoteId, payee, transferAmount, payeeReceiveAmount, payeeFspFee, payeeFspCommission, ilpPacket, condition, errorInformation, extensionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualQuoteResult {\n");
    sb.append("    quoteId: ").append(toIndentedString(quoteId)).append("\n");
    sb.append("    payee: ").append(toIndentedString(payee)).append("\n");
    sb.append("    transferAmount: ").append(toIndentedString(transferAmount)).append("\n");
    sb.append("    payeeReceiveAmount: ").append(toIndentedString(payeeReceiveAmount)).append("\n");
    sb.append("    payeeFspFee: ").append(toIndentedString(payeeFspFee)).append("\n");
    sb.append("    payeeFspCommission: ").append(toIndentedString(payeeFspCommission)).append("\n");
    sb.append("    ilpPacket: ").append(toIndentedString(ilpPacket)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    errorInformation: ").append(toIndentedString(errorInformation)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("quoteId", "payee", "transferAmount", "payeeReceiveAmount", "payeeFspFee", "payeeFspCommission", "ilpPacket", "condition", "errorInformation", "extensionList"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("quoteId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IndividualQuoteResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IndividualQuoteResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in IndividualQuoteResult is not found in the empty JSON string", IndividualQuoteResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IndividualQuoteResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `IndividualQuoteResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : IndividualQuoteResult.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("quoteId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `quoteId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quoteId").toString()));
      }
      // validate the optional field `payee`
      if (jsonObj.get("payee") != null && !jsonObj.get("payee").isJsonNull()) {
        Party.validateJsonElement(jsonObj.get("payee"));
      }
      // validate the optional field `transferAmount`
      if (jsonObj.get("transferAmount") != null && !jsonObj.get("transferAmount").isJsonNull()) {
        Money.validateJsonElement(jsonObj.get("transferAmount"));
      }
      // validate the optional field `payeeReceiveAmount`
      if (jsonObj.get("payeeReceiveAmount") != null && !jsonObj.get("payeeReceiveAmount").isJsonNull()) {
        Money.validateJsonElement(jsonObj.get("payeeReceiveAmount"));
      }
      // validate the optional field `payeeFspFee`
      if (jsonObj.get("payeeFspFee") != null && !jsonObj.get("payeeFspFee").isJsonNull()) {
        Money.validateJsonElement(jsonObj.get("payeeFspFee"));
      }
      // validate the optional field `payeeFspCommission`
      if (jsonObj.get("payeeFspCommission") != null && !jsonObj.get("payeeFspCommission").isJsonNull()) {
        Money.validateJsonElement(jsonObj.get("payeeFspCommission"));
      }
      if ((jsonObj.get("ilpPacket") != null && !jsonObj.get("ilpPacket").isJsonNull()) && !jsonObj.get("ilpPacket").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ilpPacket` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ilpPacket").toString()));
      }
      if ((jsonObj.get("condition") != null && !jsonObj.get("condition").isJsonNull()) && !jsonObj.get("condition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `condition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("condition").toString()));
      }
      // validate the optional field `errorInformation`
      if (jsonObj.get("errorInformation") != null && !jsonObj.get("errorInformation").isJsonNull()) {
        ErrorInformation.validateJsonElement(jsonObj.get("errorInformation"));
      }
      // validate the optional field `extensionList`
      if (jsonObj.get("extensionList") != null && !jsonObj.get("extensionList").isJsonNull()) {
        ExtensionList.validateJsonElement(jsonObj.get("extensionList"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IndividualQuoteResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IndividualQuoteResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IndividualQuoteResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IndividualQuoteResult.class));

       return (TypeAdapter<T>) new TypeAdapter<IndividualQuoteResult>() {
           @Override
           public void write(JsonWriter out, IndividualQuoteResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IndividualQuoteResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IndividualQuoteResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IndividualQuoteResult
   * @throws IOException if the JSON string is invalid with respect to IndividualQuoteResult
   */
  public static IndividualQuoteResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IndividualQuoteResult.class);
  }

  /**
   * Convert an instance of IndividualQuoteResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

