/*
 * Copyright (c) 2024-2026 ThitsaWorks Pte. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ExtensionList;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.Money;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * Data model for the complex type IndividualTransfer.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class IndividualTransfer {
  public static final String SERIALIZED_NAME_TRANSFER_ID = "transferId";
  @SerializedName(SERIALIZED_NAME_TRANSFER_ID)
  @javax.annotation.Nonnull
  private String transferId;

  public static final String SERIALIZED_NAME_TRANSFER_AMOUNT = "transferAmount";
  @SerializedName(SERIALIZED_NAME_TRANSFER_AMOUNT)
  @javax.annotation.Nonnull
  private Money transferAmount;

  public static final String SERIALIZED_NAME_ILP_PACKET = "ilpPacket";
  @SerializedName(SERIALIZED_NAME_ILP_PACKET)
  @javax.annotation.Nonnull
  private String ilpPacket;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  @javax.annotation.Nonnull
  private String condition;

  public static final String SERIALIZED_NAME_EXTENSION_LIST = "extensionList";
  @SerializedName(SERIALIZED_NAME_EXTENSION_LIST)
  @javax.annotation.Nullable
  private ExtensionList extensionList;

  public IndividualTransfer() {
  }

  public IndividualTransfer transferId(@javax.annotation.Nonnull String transferId) {
    this.transferId = transferId;
    return this;
  }

  /**
   * Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to [RFC 4122](https://tools.ietf.org/html/rfc4122), that is restricted by a regular expression for interoperability reasons. A UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
   * @return transferId
   */
  @javax.annotation.Nonnull
  public String getTransferId() {
    return transferId;
  }

  public void setTransferId(@javax.annotation.Nonnull String transferId) {
    this.transferId = transferId;
  }


  public IndividualTransfer transferAmount(@javax.annotation.Nonnull Money transferAmount) {
    this.transferAmount = transferAmount;
    return this;
  }

  /**
   * Get transferAmount
   * @return transferAmount
   */
  @javax.annotation.Nonnull
  public Money getTransferAmount() {
    return transferAmount;
  }

  public void setTransferAmount(@javax.annotation.Nonnull Money transferAmount) {
    this.transferAmount = transferAmount;
  }


  public IndividualTransfer ilpPacket(@javax.annotation.Nonnull String ilpPacket) {
    this.ilpPacket = ilpPacket;
    return this;
  }

  /**
   * Information for recipient (transport layer information).
   * @return ilpPacket
   */
  @javax.annotation.Nonnull
  public String getIlpPacket() {
    return ilpPacket;
  }

  public void setIlpPacket(@javax.annotation.Nonnull String ilpPacket) {
    this.ilpPacket = ilpPacket;
  }


  public IndividualTransfer condition(@javax.annotation.Nonnull String condition) {
    this.condition = condition;
    return this;
  }

  /**
   * Condition that must be attached to the transfer by the Payer.
   * @return condition
   */
  @javax.annotation.Nonnull
  public String getCondition() {
    return condition;
  }

  public void setCondition(@javax.annotation.Nonnull String condition) {
    this.condition = condition;
  }


  public IndividualTransfer extensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

  /**
   * Get extensionList
   * @return extensionList
   */
  @javax.annotation.Nullable
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndividualTransfer individualTransfer = (IndividualTransfer) o;
    return Objects.equals(this.transferId, individualTransfer.transferId) &&
        Objects.equals(this.transferAmount, individualTransfer.transferAmount) &&
        Objects.equals(this.ilpPacket, individualTransfer.ilpPacket) &&
        Objects.equals(this.condition, individualTransfer.condition) &&
        Objects.equals(this.extensionList, individualTransfer.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferId, transferAmount, ilpPacket, condition, extensionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualTransfer {\n");
    sb.append("    transferId: ").append(toIndentedString(transferId)).append("\n");
    sb.append("    transferAmount: ").append(toIndentedString(transferAmount)).append("\n");
    sb.append("    ilpPacket: ").append(toIndentedString(ilpPacket)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("transferId", "transferAmount", "ilpPacket", "condition", "extensionList"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("transferId", "transferAmount", "ilpPacket", "condition"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to IndividualTransfer
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!IndividualTransfer.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in IndividualTransfer is not found in the empty JSON string", IndividualTransfer.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!IndividualTransfer.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `IndividualTransfer` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : IndividualTransfer.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("transferId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transferId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transferId").toString()));
      }
      // validate the required field `transferAmount`
      Money.validateJsonElement(jsonObj.get("transferAmount"));
      if (!jsonObj.get("ilpPacket").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ilpPacket` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ilpPacket").toString()));
      }
      if (!jsonObj.get("condition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `condition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("condition").toString()));
      }
      // validate the optional field `extensionList`
      if (jsonObj.get("extensionList") != null && !jsonObj.get("extensionList").isJsonNull()) {
        ExtensionList.validateJsonElement(jsonObj.get("extensionList"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!IndividualTransfer.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'IndividualTransfer' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<IndividualTransfer> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(IndividualTransfer.class));

       return (TypeAdapter<T>) new TypeAdapter<IndividualTransfer>() {
           @Override
           public void write(JsonWriter out, IndividualTransfer value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public IndividualTransfer read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of IndividualTransfer given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of IndividualTransfer
   * @throws IOException if the JSON string is invalid with respect to IndividualTransfer
   */
  public static IndividualTransfer fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, IndividualTransfer.class);
  }

  /**
   * Convert an instance of IndividualTransfer to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

