/*
 * Copyright (c) 2026 ThitsaWorks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.Currency;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.PartyIdInfo;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.PartyPersonalInfo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * Data model for the complex type Party.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class Party {
  public static final String SERIALIZED_NAME_PARTY_ID_INFO = "partyIdInfo";
  @SerializedName(SERIALIZED_NAME_PARTY_ID_INFO)
  @javax.annotation.Nonnull
  private PartyIdInfo partyIdInfo;

  public static final String SERIALIZED_NAME_MERCHANT_CLASSIFICATION_CODE = "merchantClassificationCode";
  @SerializedName(SERIALIZED_NAME_MERCHANT_CLASSIFICATION_CODE)
  @javax.annotation.Nullable
  private String merchantClassificationCode;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nullable
  private String name;

  public static final String SERIALIZED_NAME_PERSONAL_INFO = "personalInfo";
  @SerializedName(SERIALIZED_NAME_PERSONAL_INFO)
  @javax.annotation.Nullable
  private PartyPersonalInfo personalInfo;

  public static final String SERIALIZED_NAME_SUPPORTED_CURRENCIES = "supportedCurrencies";
  @SerializedName(SERIALIZED_NAME_SUPPORTED_CURRENCIES)
  @javax.annotation.Nullable
  private List<Currency> supportedCurrencies = new ArrayList<>();

  public Party() {
  }

  public Party partyIdInfo(@javax.annotation.Nonnull PartyIdInfo partyIdInfo) {
    this.partyIdInfo = partyIdInfo;
    return this;
  }

  /**
   * Get partyIdInfo
   * @return partyIdInfo
   */
  @javax.annotation.Nonnull
  public PartyIdInfo getPartyIdInfo() {
    return partyIdInfo;
  }

  public void setPartyIdInfo(@javax.annotation.Nonnull PartyIdInfo partyIdInfo) {
    this.partyIdInfo = partyIdInfo;
  }


  public Party merchantClassificationCode(@javax.annotation.Nullable String merchantClassificationCode) {
    this.merchantClassificationCode = merchantClassificationCode;
    return this;
  }

  /**
   * A limited set of pre-defined numbers. This list would be a limited set of numbers identifying a set of popular merchant types like School Fees, Pubs and Restaurants, Groceries, etc.
   * @return merchantClassificationCode
   */
  @javax.annotation.Nullable
  public String getMerchantClassificationCode() {
    return merchantClassificationCode;
  }

  public void setMerchantClassificationCode(@javax.annotation.Nullable String merchantClassificationCode) {
    this.merchantClassificationCode = merchantClassificationCode;
  }


  public Party name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Name of the Party. Could be a real name or a nickname.
   * @return name
   */
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public Party personalInfo(@javax.annotation.Nullable PartyPersonalInfo personalInfo) {
    this.personalInfo = personalInfo;
    return this;
  }

  /**
   * Get personalInfo
   * @return personalInfo
   */
  @javax.annotation.Nullable
  public PartyPersonalInfo getPersonalInfo() {
    return personalInfo;
  }

  public void setPersonalInfo(@javax.annotation.Nullable PartyPersonalInfo personalInfo) {
    this.personalInfo = personalInfo;
  }


  public Party supportedCurrencies(@javax.annotation.Nullable List<Currency> supportedCurrencies) {
    this.supportedCurrencies = supportedCurrencies;
    return this;
  }

  public Party addSupportedCurrenciesItem(Currency supportedCurrenciesItem) {
    if (this.supportedCurrencies == null) {
      this.supportedCurrencies = new ArrayList<>();
    }
    this.supportedCurrencies.add(supportedCurrenciesItem);
    return this;
  }

  /**
   * Currencies in which the party can receive funds.
   * @return supportedCurrencies
   */
  @javax.annotation.Nullable
  public List<Currency> getSupportedCurrencies() {
    return supportedCurrencies;
  }

  public void setSupportedCurrencies(@javax.annotation.Nullable List<Currency> supportedCurrencies) {
    this.supportedCurrencies = supportedCurrencies;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Party party = (Party) o;
    return Objects.equals(this.partyIdInfo, party.partyIdInfo) &&
        Objects.equals(this.merchantClassificationCode, party.merchantClassificationCode) &&
        Objects.equals(this.name, party.name) &&
        Objects.equals(this.personalInfo, party.personalInfo) &&
        Objects.equals(this.supportedCurrencies, party.supportedCurrencies);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyIdInfo, merchantClassificationCode, name, personalInfo, supportedCurrencies);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Party {\n");
    sb.append("    partyIdInfo: ").append(toIndentedString(partyIdInfo)).append("\n");
    sb.append("    merchantClassificationCode: ").append(toIndentedString(merchantClassificationCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    personalInfo: ").append(toIndentedString(personalInfo)).append("\n");
    sb.append("    supportedCurrencies: ").append(toIndentedString(supportedCurrencies)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("partyIdInfo", "merchantClassificationCode", "name", "personalInfo", "supportedCurrencies"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("partyIdInfo"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Party
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Party.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in Party is not found in the empty JSON string", Party.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Party.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `Party` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Party.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `partyIdInfo`
      PartyIdInfo.validateJsonElement(jsonObj.get("partyIdInfo"));
      if ((jsonObj.get("merchantClassificationCode") != null && !jsonObj.get("merchantClassificationCode").isJsonNull()) && !jsonObj.get("merchantClassificationCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `merchantClassificationCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantClassificationCode").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      // validate the optional field `personalInfo`
      if (jsonObj.get("personalInfo") != null && !jsonObj.get("personalInfo").isJsonNull()) {
        PartyPersonalInfo.validateJsonElement(jsonObj.get("personalInfo"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("supportedCurrencies") != null && !jsonObj.get("supportedCurrencies").isJsonNull() && !jsonObj.get("supportedCurrencies").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `supportedCurrencies` to be an array in the JSON string but got `%s`", jsonObj.get("supportedCurrencies").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Party.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Party' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Party> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Party.class));

       return (TypeAdapter<T>) new TypeAdapter<Party>() {
           @Override
           public void write(JsonWriter out, Party value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Party read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Party given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Party
   * @throws IOException if the JSON string is invalid with respect to Party
   */
  public static Party fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Party.class);
  }

  /**
   * Convert an instance of Party to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

