/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.PartyComplexName;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * Data model for the complex type PartyPersonalInfo.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class PartyPersonalInfo {
  public static final String SERIALIZED_NAME_COMPLEX_NAME = "complexName";
  @SerializedName(SERIALIZED_NAME_COMPLEX_NAME)
  @javax.annotation.Nullable
  private PartyComplexName complexName;

  public static final String SERIALIZED_NAME_DATE_OF_BIRTH = "dateOfBirth";
  @SerializedName(SERIALIZED_NAME_DATE_OF_BIRTH)
  @javax.annotation.Nullable
  private String dateOfBirth;

  public static final String SERIALIZED_NAME_KYC_INFORMATION = "kycInformation";
  @SerializedName(SERIALIZED_NAME_KYC_INFORMATION)
  @javax.annotation.Nullable
  private String kycInformation;

  public PartyPersonalInfo() {
  }

  public PartyPersonalInfo complexName(@javax.annotation.Nullable PartyComplexName complexName) {
    this.complexName = complexName;
    return this;
  }

  /**
   * Get complexName
   * @return complexName
   */
  @javax.annotation.Nullable
  public PartyComplexName getComplexName() {
    return complexName;
  }

  public void setComplexName(@javax.annotation.Nullable PartyComplexName complexName) {
    this.complexName = complexName;
  }


  public PartyPersonalInfo dateOfBirth(@javax.annotation.Nullable String dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
    return this;
  }

  /**
   * Date of Birth of the Party.
   * @return dateOfBirth
   */
  @javax.annotation.Nullable
  public String getDateOfBirth() {
    return dateOfBirth;
  }

  public void setDateOfBirth(@javax.annotation.Nullable String dateOfBirth) {
    this.dateOfBirth = dateOfBirth;
  }


  public PartyPersonalInfo kycInformation(@javax.annotation.Nullable String kycInformation) {
    this.kycInformation = kycInformation;
    return this;
  }

  /**
   * KYC information for the party in a form mandated by an individual scheme.
   * @return kycInformation
   */
  @javax.annotation.Nullable
  public String getKycInformation() {
    return kycInformation;
  }

  public void setKycInformation(@javax.annotation.Nullable String kycInformation) {
    this.kycInformation = kycInformation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartyPersonalInfo partyPersonalInfo = (PartyPersonalInfo) o;
    return Objects.equals(this.complexName, partyPersonalInfo.complexName) &&
        Objects.equals(this.dateOfBirth, partyPersonalInfo.dateOfBirth) &&
        Objects.equals(this.kycInformation, partyPersonalInfo.kycInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(complexName, dateOfBirth, kycInformation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartyPersonalInfo {\n");
    sb.append("    complexName: ").append(toIndentedString(complexName)).append("\n");
    sb.append("    dateOfBirth: ").append(toIndentedString(dateOfBirth)).append("\n");
    sb.append("    kycInformation: ").append(toIndentedString(kycInformation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("complexName", "dateOfBirth", "kycInformation"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PartyPersonalInfo
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PartyPersonalInfo.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in PartyPersonalInfo is not found in the empty JSON string", PartyPersonalInfo.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PartyPersonalInfo.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `PartyPersonalInfo` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `complexName`
      if (jsonObj.get("complexName") != null && !jsonObj.get("complexName").isJsonNull()) {
        PartyComplexName.validateJsonElement(jsonObj.get("complexName"));
      }
      if ((jsonObj.get("dateOfBirth") != null && !jsonObj.get("dateOfBirth").isJsonNull()) && !jsonObj.get("dateOfBirth").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `dateOfBirth` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dateOfBirth").toString()));
      }
      if ((jsonObj.get("kycInformation") != null && !jsonObj.get("kycInformation").isJsonNull()) && !jsonObj.get("kycInformation").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `kycInformation` to be a primitive type in the JSON string but got `%s`", jsonObj.get("kycInformation").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PartyPersonalInfo.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PartyPersonalInfo' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PartyPersonalInfo> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PartyPersonalInfo.class));

       return (TypeAdapter<T>) new TypeAdapter<PartyPersonalInfo>() {
           @Override
           public void write(JsonWriter out, PartyPersonalInfo value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PartyPersonalInfo read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PartyPersonalInfo given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PartyPersonalInfo
   * @throws IOException if the JSON string is invalid with respect to PartyPersonalInfo
   */
  public static PartyPersonalInfo fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PartyPersonalInfo.class);
  }

  /**
   * Convert an instance of PartyPersonalInfo to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

