/*
 * Copyright (c) 2024-2026 ThitsaWorks Pte. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.AmountType;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.CurrencyConverter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ExtensionList;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.FxRate;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.GeoCode;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.Money;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.Party;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransactionType;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * The object sent in the POST /quotes request.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class QuotesPostRequest {
  public static final String SERIALIZED_NAME_QUOTE_ID = "quoteId";
  @SerializedName(SERIALIZED_NAME_QUOTE_ID)
  @javax.annotation.Nonnull
  private String quoteId;

  public static final String SERIALIZED_NAME_TRANSACTION_ID = "transactionId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_ID)
  @javax.annotation.Nonnull
  private String transactionId;

  public static final String SERIALIZED_NAME_TRANSACTION_REQUEST_ID = "transactionRequestId";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_REQUEST_ID)
  @javax.annotation.Nullable
  private String transactionRequestId;

  public static final String SERIALIZED_NAME_PAYEE = "payee";
  @SerializedName(SERIALIZED_NAME_PAYEE)
  @javax.annotation.Nonnull
  private Party payee;

  public static final String SERIALIZED_NAME_PAYER = "payer";
  @SerializedName(SERIALIZED_NAME_PAYER)
  @javax.annotation.Nonnull
  private Party payer;

  public static final String SERIALIZED_NAME_AMOUNT_TYPE = "amountType";
  @SerializedName(SERIALIZED_NAME_AMOUNT_TYPE)
  @javax.annotation.Nonnull
  private AmountType amountType;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  @javax.annotation.Nonnull
  private Money amount;

  public static final String SERIALIZED_NAME_FEES = "fees";
  @SerializedName(SERIALIZED_NAME_FEES)
  @javax.annotation.Nullable
  private Money fees;

  public static final String SERIALIZED_NAME_TRANSACTION_TYPE = "transactionType";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_TYPE)
  @javax.annotation.Nonnull
  private TransactionType transactionType;

  public static final String SERIALIZED_NAME_CONVERTER = "converter";
  @SerializedName(SERIALIZED_NAME_CONVERTER)
  @javax.annotation.Nullable
  private CurrencyConverter converter;

  public static final String SERIALIZED_NAME_CURRENCY_CONVERSION = "currencyConversion";
  @SerializedName(SERIALIZED_NAME_CURRENCY_CONVERSION)
  @javax.annotation.Nullable
  private FxRate currencyConversion;

  public static final String SERIALIZED_NAME_GEO_CODE = "geoCode";
  @SerializedName(SERIALIZED_NAME_GEO_CODE)
  @javax.annotation.Nullable
  private GeoCode geoCode;

  public static final String SERIALIZED_NAME_NOTE = "note";
  @SerializedName(SERIALIZED_NAME_NOTE)
  @javax.annotation.Nullable
  private String note;

  public static final String SERIALIZED_NAME_EXPIRATION = "expiration";
  @SerializedName(SERIALIZED_NAME_EXPIRATION)
  @javax.annotation.Nullable
  private String expiration;

  public static final String SERIALIZED_NAME_EXTENSION_LIST = "extensionList";
  @SerializedName(SERIALIZED_NAME_EXTENSION_LIST)
  @javax.annotation.Nullable
  private ExtensionList extensionList;

  public QuotesPostRequest() {
  }

  public QuotesPostRequest quoteId(@javax.annotation.Nonnull String quoteId) {
    this.quoteId = quoteId;
    return this;
  }

  /**
   * Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to [RFC 4122](https://tools.ietf.org/html/rfc4122), that is restricted by a regular expression for interoperability reasons. A UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
   * @return quoteId
   */
  @javax.annotation.Nonnull
  public String getQuoteId() {
    return quoteId;
  }

  public void setQuoteId(@javax.annotation.Nonnull String quoteId) {
    this.quoteId = quoteId;
  }


  public QuotesPostRequest transactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
    return this;
  }

  /**
   * Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to [RFC 4122](https://tools.ietf.org/html/rfc4122), that is restricted by a regular expression for interoperability reasons. A UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
   * @return transactionId
   */
  @javax.annotation.Nonnull
  public String getTransactionId() {
    return transactionId;
  }

  public void setTransactionId(@javax.annotation.Nonnull String transactionId) {
    this.transactionId = transactionId;
  }


  public QuotesPostRequest transactionRequestId(@javax.annotation.Nullable String transactionRequestId) {
    this.transactionRequestId = transactionRequestId;
    return this;
  }

  /**
   * Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to [RFC 4122](https://tools.ietf.org/html/rfc4122), that is restricted by a regular expression for interoperability reasons. A UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
   * @return transactionRequestId
   */
  @javax.annotation.Nullable
  public String getTransactionRequestId() {
    return transactionRequestId;
  }

  public void setTransactionRequestId(@javax.annotation.Nullable String transactionRequestId) {
    this.transactionRequestId = transactionRequestId;
  }


  public QuotesPostRequest payee(@javax.annotation.Nonnull Party payee) {
    this.payee = payee;
    return this;
  }

  /**
   * Get payee
   * @return payee
   */
  @javax.annotation.Nonnull
  public Party getPayee() {
    return payee;
  }

  public void setPayee(@javax.annotation.Nonnull Party payee) {
    this.payee = payee;
  }


  public QuotesPostRequest payer(@javax.annotation.Nonnull Party payer) {
    this.payer = payer;
    return this;
  }

  /**
   * Get payer
   * @return payer
   */
  @javax.annotation.Nonnull
  public Party getPayer() {
    return payer;
  }

  public void setPayer(@javax.annotation.Nonnull Party payer) {
    this.payer = payer;
  }


  public QuotesPostRequest amountType(@javax.annotation.Nonnull AmountType amountType) {
    this.amountType = amountType;
    return this;
  }

  /**
   * Get amountType
   * @return amountType
   */
  @javax.annotation.Nonnull
  public AmountType getAmountType() {
    return amountType;
  }

  public void setAmountType(@javax.annotation.Nonnull AmountType amountType) {
    this.amountType = amountType;
  }


  public QuotesPostRequest amount(@javax.annotation.Nonnull Money amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @javax.annotation.Nonnull
  public Money getAmount() {
    return amount;
  }

  public void setAmount(@javax.annotation.Nonnull Money amount) {
    this.amount = amount;
  }


  public QuotesPostRequest fees(@javax.annotation.Nullable Money fees) {
    this.fees = fees;
    return this;
  }

  /**
   * Get fees
   * @return fees
   */
  @javax.annotation.Nullable
  public Money getFees() {
    return fees;
  }

  public void setFees(@javax.annotation.Nullable Money fees) {
    this.fees = fees;
  }


  public QuotesPostRequest transactionType(@javax.annotation.Nonnull TransactionType transactionType) {
    this.transactionType = transactionType;
    return this;
  }

  /**
   * Get transactionType
   * @return transactionType
   */
  @javax.annotation.Nonnull
  public TransactionType getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(@javax.annotation.Nonnull TransactionType transactionType) {
    this.transactionType = transactionType;
  }


  public QuotesPostRequest converter(@javax.annotation.Nullable CurrencyConverter converter) {
    this.converter = converter;
    return this;
  }

  /**
   * An optional field which will allow the payer DFSP to specify which DFSP it wants to undertake currency conversion. This is useful incase of if the sender wants the recipient to receive a specified amount of the target currency, but the payer DFSP does not want to undertake the currency conversion. In this case, the amount of the transfer would be expressed in the target currency and the amountType would be set to RECEIVE.
   * @return converter
   */
  @javax.annotation.Nullable
  public CurrencyConverter getConverter() {
    return converter;
  }

  public void setConverter(@javax.annotation.Nullable CurrencyConverter converter) {
    this.converter = converter;
  }


  public QuotesPostRequest currencyConversion(@javax.annotation.Nullable FxRate currencyConversion) {
    this.currencyConversion = currencyConversion;
    return this;
  }

  /**
   * Used by the debtor party if it wants to share information about the currency conversion it proposes to make; or if it is required by scheme rules to share this information. This object contains the amount of the transfer in the source and target currencies, but does not identify the FXP being used.
   * @return currencyConversion
   */
  @javax.annotation.Nullable
  public FxRate getCurrencyConversion() {
    return currencyConversion;
  }

  public void setCurrencyConversion(@javax.annotation.Nullable FxRate currencyConversion) {
    this.currencyConversion = currencyConversion;
  }


  public QuotesPostRequest geoCode(@javax.annotation.Nullable GeoCode geoCode) {
    this.geoCode = geoCode;
    return this;
  }

  /**
   * Get geoCode
   * @return geoCode
   */
  @javax.annotation.Nullable
  public GeoCode getGeoCode() {
    return geoCode;
  }

  public void setGeoCode(@javax.annotation.Nullable GeoCode geoCode) {
    this.geoCode = geoCode;
  }


  public QuotesPostRequest note(@javax.annotation.Nullable String note) {
    this.note = note;
    return this;
  }

  /**
   * Memo assigned to transaction.
   * @return note
   */
  @javax.annotation.Nullable
  public String getNote() {
    return note;
  }

  public void setNote(@javax.annotation.Nullable String note) {
    this.note = note;
  }


  public QuotesPostRequest expiration(@javax.annotation.Nullable String expiration) {
    this.expiration = expiration;
    return this;
  }

  /**
   * The API data type DateTime is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons. The format is according to [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html), expressed in a combined date, time and time zone format. A more readable version of the format is yyyy-MM-ddTHH:mm:ss.SSS[-HH:MM]. Examples are \&quot;2016-05-24T08:38:08.699-04:00\&quot;, \&quot;2016-05-24T08:38:08.699Z\&quot; (where Z indicates Zulu time zone, same as UTC).
   * @return expiration
   */
  @javax.annotation.Nullable
  public String getExpiration() {
    return expiration;
  }

  public void setExpiration(@javax.annotation.Nullable String expiration) {
    this.expiration = expiration;
  }


  public QuotesPostRequest extensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

  /**
   * Get extensionList
   * @return extensionList
   */
  @javax.annotation.Nullable
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuotesPostRequest quotesPostRequest = (QuotesPostRequest) o;
    return Objects.equals(this.quoteId, quotesPostRequest.quoteId) &&
        Objects.equals(this.transactionId, quotesPostRequest.transactionId) &&
        Objects.equals(this.transactionRequestId, quotesPostRequest.transactionRequestId) &&
        Objects.equals(this.payee, quotesPostRequest.payee) &&
        Objects.equals(this.payer, quotesPostRequest.payer) &&
        Objects.equals(this.amountType, quotesPostRequest.amountType) &&
        Objects.equals(this.amount, quotesPostRequest.amount) &&
        Objects.equals(this.fees, quotesPostRequest.fees) &&
        Objects.equals(this.transactionType, quotesPostRequest.transactionType) &&
        Objects.equals(this.converter, quotesPostRequest.converter) &&
        Objects.equals(this.currencyConversion, quotesPostRequest.currencyConversion) &&
        Objects.equals(this.geoCode, quotesPostRequest.geoCode) &&
        Objects.equals(this.note, quotesPostRequest.note) &&
        Objects.equals(this.expiration, quotesPostRequest.expiration) &&
        Objects.equals(this.extensionList, quotesPostRequest.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(quoteId, transactionId, transactionRequestId, payee, payer, amountType, amount, fees, transactionType, converter, currencyConversion, geoCode, note, expiration, extensionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuotesPostRequest {\n");
    sb.append("    quoteId: ").append(toIndentedString(quoteId)).append("\n");
    sb.append("    transactionId: ").append(toIndentedString(transactionId)).append("\n");
    sb.append("    transactionRequestId: ").append(toIndentedString(transactionRequestId)).append("\n");
    sb.append("    payee: ").append(toIndentedString(payee)).append("\n");
    sb.append("    payer: ").append(toIndentedString(payer)).append("\n");
    sb.append("    amountType: ").append(toIndentedString(amountType)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    fees: ").append(toIndentedString(fees)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    converter: ").append(toIndentedString(converter)).append("\n");
    sb.append("    currencyConversion: ").append(toIndentedString(currencyConversion)).append("\n");
    sb.append("    geoCode: ").append(toIndentedString(geoCode)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("quoteId", "transactionId", "transactionRequestId", "payee", "payer", "amountType", "amount", "fees", "transactionType", "converter", "currencyConversion", "geoCode", "note", "expiration", "extensionList"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("quoteId", "transactionId", "payee", "payer", "amountType", "amount", "transactionType"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to QuotesPostRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!QuotesPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in QuotesPostRequest is not found in the empty JSON string", QuotesPostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!QuotesPostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `QuotesPostRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : QuotesPostRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("quoteId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `quoteId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quoteId").toString()));
      }
      if (!jsonObj.get("transactionId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transactionId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionId").toString()));
      }
      if ((jsonObj.get("transactionRequestId") != null && !jsonObj.get("transactionRequestId").isJsonNull()) && !jsonObj.get("transactionRequestId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transactionRequestId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transactionRequestId").toString()));
      }
      // validate the required field `payee`
      Party.validateJsonElement(jsonObj.get("payee"));
      // validate the required field `payer`
      Party.validateJsonElement(jsonObj.get("payer"));
      // validate the required field `amountType`
      AmountType.validateJsonElement(jsonObj.get("amountType"));
      // validate the required field `amount`
      Money.validateJsonElement(jsonObj.get("amount"));
      // validate the optional field `fees`
      if (jsonObj.get("fees") != null && !jsonObj.get("fees").isJsonNull()) {
        Money.validateJsonElement(jsonObj.get("fees"));
      }
      // validate the required field `transactionType`
      TransactionType.validateJsonElement(jsonObj.get("transactionType"));
      // validate the optional field `converter`
      if (jsonObj.get("converter") != null && !jsonObj.get("converter").isJsonNull()) {
        CurrencyConverter.validateJsonElement(jsonObj.get("converter"));
      }
      // validate the optional field `currencyConversion`
      if (jsonObj.get("currencyConversion") != null && !jsonObj.get("currencyConversion").isJsonNull()) {
        FxRate.validateJsonElement(jsonObj.get("currencyConversion"));
      }
      // validate the optional field `geoCode`
      if (jsonObj.get("geoCode") != null && !jsonObj.get("geoCode").isJsonNull()) {
        GeoCode.validateJsonElement(jsonObj.get("geoCode"));
      }
      if ((jsonObj.get("note") != null && !jsonObj.get("note").isJsonNull()) && !jsonObj.get("note").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `note` to be a primitive type in the JSON string but got `%s`", jsonObj.get("note").toString()));
      }
      if ((jsonObj.get("expiration") != null && !jsonObj.get("expiration").isJsonNull()) && !jsonObj.get("expiration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `expiration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiration").toString()));
      }
      // validate the optional field `extensionList`
      if (jsonObj.get("extensionList") != null && !jsonObj.get("extensionList").isJsonNull()) {
        ExtensionList.validateJsonElement(jsonObj.get("extensionList"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!QuotesPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'QuotesPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<QuotesPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(QuotesPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<QuotesPostRequest>() {
           @Override
           public void write(JsonWriter out, QuotesPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public QuotesPostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of QuotesPostRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of QuotesPostRequest
   * @throws IOException if the JSON string is invalid with respect to QuotesPostRequest
   */
  public static QuotesPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, QuotesPostRequest.class);
  }

  /**
   * Convert an instance of QuotesPostRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

