/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ExtensionList;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.Money;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * The object sent in the POST /transfers request.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class TransfersPostRequest {
  public static final String SERIALIZED_NAME_TRANSFER_ID = "transferId";
  @SerializedName(SERIALIZED_NAME_TRANSFER_ID)
  @javax.annotation.Nonnull
  private String transferId;

  public static final String SERIALIZED_NAME_PAYEE_FSP = "payeeFsp";
  @SerializedName(SERIALIZED_NAME_PAYEE_FSP)
  @javax.annotation.Nonnull
  private String payeeFsp;

  public static final String SERIALIZED_NAME_PAYER_FSP = "payerFsp";
  @SerializedName(SERIALIZED_NAME_PAYER_FSP)
  @javax.annotation.Nonnull
  private String payerFsp;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  @javax.annotation.Nonnull
  private Money amount;

  public static final String SERIALIZED_NAME_ILP_PACKET = "ilpPacket";
  @SerializedName(SERIALIZED_NAME_ILP_PACKET)
  @javax.annotation.Nonnull
  private String ilpPacket;

  public static final String SERIALIZED_NAME_CONDITION = "condition";
  @SerializedName(SERIALIZED_NAME_CONDITION)
  @javax.annotation.Nonnull
  private String condition;

  public static final String SERIALIZED_NAME_EXPIRATION = "expiration";
  @SerializedName(SERIALIZED_NAME_EXPIRATION)
  @javax.annotation.Nonnull
  private String expiration;

  public static final String SERIALIZED_NAME_EXTENSION_LIST = "extensionList";
  @SerializedName(SERIALIZED_NAME_EXTENSION_LIST)
  @javax.annotation.Nullable
  private ExtensionList extensionList;

  public TransfersPostRequest() {
  }

  public TransfersPostRequest transferId(@javax.annotation.Nonnull String transferId) {
    this.transferId = transferId;
    return this;
  }

  /**
   * Identifier that correlates all messages of the same sequence. The API data type UUID (Universally Unique Identifier) is a JSON String in canonical format, conforming to [RFC 4122](https://tools.ietf.org/html/rfc4122), that is restricted by a regular expression for interoperability reasons. A UUID is always 36 characters long, 32 hexadecimal symbols and 4 dashes (‘-‘).
   * @return transferId
   */
  @javax.annotation.Nonnull
  public String getTransferId() {
    return transferId;
  }

  public void setTransferId(@javax.annotation.Nonnull String transferId) {
    this.transferId = transferId;
  }


  public TransfersPostRequest payeeFsp(@javax.annotation.Nonnull String payeeFsp) {
    this.payeeFsp = payeeFsp;
    return this;
  }

  /**
   * FSP identifier.
   * @return payeeFsp
   */
  @javax.annotation.Nonnull
  public String getPayeeFsp() {
    return payeeFsp;
  }

  public void setPayeeFsp(@javax.annotation.Nonnull String payeeFsp) {
    this.payeeFsp = payeeFsp;
  }


  public TransfersPostRequest payerFsp(@javax.annotation.Nonnull String payerFsp) {
    this.payerFsp = payerFsp;
    return this;
  }

  /**
   * FSP identifier.
   * @return payerFsp
   */
  @javax.annotation.Nonnull
  public String getPayerFsp() {
    return payerFsp;
  }

  public void setPayerFsp(@javax.annotation.Nonnull String payerFsp) {
    this.payerFsp = payerFsp;
  }


  public TransfersPostRequest amount(@javax.annotation.Nonnull Money amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @javax.annotation.Nonnull
  public Money getAmount() {
    return amount;
  }

  public void setAmount(@javax.annotation.Nonnull Money amount) {
    this.amount = amount;
  }


  public TransfersPostRequest ilpPacket(@javax.annotation.Nonnull String ilpPacket) {
    this.ilpPacket = ilpPacket;
    return this;
  }

  /**
   * Information for recipient (transport layer information).
   * @return ilpPacket
   */
  @javax.annotation.Nonnull
  public String getIlpPacket() {
    return ilpPacket;
  }

  public void setIlpPacket(@javax.annotation.Nonnull String ilpPacket) {
    this.ilpPacket = ilpPacket;
  }


  public TransfersPostRequest condition(@javax.annotation.Nonnull String condition) {
    this.condition = condition;
    return this;
  }

  /**
   * Condition that must be attached to the transfer by the Payer.
   * @return condition
   */
  @javax.annotation.Nonnull
  public String getCondition() {
    return condition;
  }

  public void setCondition(@javax.annotation.Nonnull String condition) {
    this.condition = condition;
  }


  public TransfersPostRequest expiration(@javax.annotation.Nonnull String expiration) {
    this.expiration = expiration;
    return this;
  }

  /**
   * The API data type DateTime is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons. The format is according to [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html), expressed in a combined date, time and time zone format. A more readable version of the format is yyyy-MM-ddTHH:mm:ss.SSS[-HH:MM]. Examples are \&quot;2016-05-24T08:38:08.699-04:00\&quot;, \&quot;2016-05-24T08:38:08.699Z\&quot; (where Z indicates Zulu time zone, same as UTC).
   * @return expiration
   */
  @javax.annotation.Nonnull
  public String getExpiration() {
    return expiration;
  }

  public void setExpiration(@javax.annotation.Nonnull String expiration) {
    this.expiration = expiration;
  }


  public TransfersPostRequest extensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

  /**
   * Get extensionList
   * @return extensionList
   */
  @javax.annotation.Nullable
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransfersPostRequest transfersPostRequest = (TransfersPostRequest) o;
    return Objects.equals(this.transferId, transfersPostRequest.transferId) &&
        Objects.equals(this.payeeFsp, transfersPostRequest.payeeFsp) &&
        Objects.equals(this.payerFsp, transfersPostRequest.payerFsp) &&
        Objects.equals(this.amount, transfersPostRequest.amount) &&
        Objects.equals(this.ilpPacket, transfersPostRequest.ilpPacket) &&
        Objects.equals(this.condition, transfersPostRequest.condition) &&
        Objects.equals(this.expiration, transfersPostRequest.expiration) &&
        Objects.equals(this.extensionList, transfersPostRequest.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(transferId, payeeFsp, payerFsp, amount, ilpPacket, condition, expiration, extensionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransfersPostRequest {\n");
    sb.append("    transferId: ").append(toIndentedString(transferId)).append("\n");
    sb.append("    payeeFsp: ").append(toIndentedString(payeeFsp)).append("\n");
    sb.append("    payerFsp: ").append(toIndentedString(payerFsp)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    ilpPacket: ").append(toIndentedString(ilpPacket)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("transferId", "payeeFsp", "payerFsp", "amount", "ilpPacket", "condition", "expiration", "extensionList"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("transferId", "payeeFsp", "payerFsp", "amount", "ilpPacket", "condition", "expiration"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TransfersPostRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TransfersPostRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TransfersPostRequest is not found in the empty JSON string", TransfersPostRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TransfersPostRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TransfersPostRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TransfersPostRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("transferId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `transferId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("transferId").toString()));
      }
      if (!jsonObj.get("payeeFsp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payeeFsp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payeeFsp").toString()));
      }
      if (!jsonObj.get("payerFsp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `payerFsp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("payerFsp").toString()));
      }
      // validate the required field `amount`
      Money.validateJsonElement(jsonObj.get("amount"));
      if (!jsonObj.get("ilpPacket").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ilpPacket` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ilpPacket").toString()));
      }
      if (!jsonObj.get("condition").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `condition` to be a primitive type in the JSON string but got `%s`", jsonObj.get("condition").toString()));
      }
      if (!jsonObj.get("expiration").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `expiration` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expiration").toString()));
      }
      // validate the optional field `extensionList`
      if (jsonObj.get("extensionList") != null && !jsonObj.get("extensionList").isJsonNull()) {
        ExtensionList.validateJsonElement(jsonObj.get("extensionList"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransfersPostRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransfersPostRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransfersPostRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransfersPostRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<TransfersPostRequest>() {
           @Override
           public void write(JsonWriter out, TransfersPostRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TransfersPostRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TransfersPostRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TransfersPostRequest
   * @throws IOException if the JSON string is invalid with respect to TransfersPostRequest
   */
  public static TransfersPostRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransfersPostRequest.class);
  }

  /**
   * Convert an instance of TransfersPostRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

