/*
 * Copyright (c) 2024-2026 ThitsaWorks Pte. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ExtensionList;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransferState;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.thitsaworks.mojaloop.coreconnector.fspiop.JSON;

/**
 * The object sent in the PUT /transfers/{ID} callback.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-17T14:49:56.535063+07:00[Asia/Ho_Chi_Minh]", comments = "Generator version: 7.22.0")
public class TransfersIDPutResponse {
  public static final String SERIALIZED_NAME_FULFILMENT = "fulfilment";
  @SerializedName(SERIALIZED_NAME_FULFILMENT)
  @javax.annotation.Nullable
  private String fulfilment;

  public static final String SERIALIZED_NAME_COMPLETED_TIMESTAMP = "completedTimestamp";
  @SerializedName(SERIALIZED_NAME_COMPLETED_TIMESTAMP)
  @javax.annotation.Nullable
  private String completedTimestamp;

  public static final String SERIALIZED_NAME_TRANSFER_STATE = "transferState";
  @SerializedName(SERIALIZED_NAME_TRANSFER_STATE)
  @javax.annotation.Nonnull
  private TransferState transferState;

  public static final String SERIALIZED_NAME_EXTENSION_LIST = "extensionList";
  @SerializedName(SERIALIZED_NAME_EXTENSION_LIST)
  @javax.annotation.Nullable
  private ExtensionList extensionList;

  public TransfersIDPutResponse() {
  }

  public TransfersIDPutResponse fulfilment(@javax.annotation.Nullable String fulfilment) {
    this.fulfilment = fulfilment;
    return this;
  }

  /**
   * Fulfilment that must be attached to the transfer by the Payee.
   * @return fulfilment
   */
  @javax.annotation.Nullable
  public String getFulfilment() {
    return fulfilment;
  }

  public void setFulfilment(@javax.annotation.Nullable String fulfilment) {
    this.fulfilment = fulfilment;
  }


  public TransfersIDPutResponse completedTimestamp(@javax.annotation.Nullable String completedTimestamp) {
    this.completedTimestamp = completedTimestamp;
    return this;
  }

  /**
   * The API data type DateTime is a JSON String in a lexical format that is restricted by a regular expression for interoperability reasons. The format is according to [ISO 8601](https://www.iso.org/iso-8601-date-and-time-format.html), expressed in a combined date, time and time zone format. A more readable version of the format is yyyy-MM-ddTHH:mm:ss.SSS[-HH:MM]. Examples are \&quot;2016-05-24T08:38:08.699-04:00\&quot;, \&quot;2016-05-24T08:38:08.699Z\&quot; (where Z indicates Zulu time zone, same as UTC).
   * @return completedTimestamp
   */
  @javax.annotation.Nullable
  public String getCompletedTimestamp() {
    return completedTimestamp;
  }

  public void setCompletedTimestamp(@javax.annotation.Nullable String completedTimestamp) {
    this.completedTimestamp = completedTimestamp;
  }


  public TransfersIDPutResponse transferState(@javax.annotation.Nonnull TransferState transferState) {
    this.transferState = transferState;
    return this;
  }

  /**
   * Get transferState
   * @return transferState
   */
  @javax.annotation.Nonnull
  public TransferState getTransferState() {
    return transferState;
  }

  public void setTransferState(@javax.annotation.Nonnull TransferState transferState) {
    this.transferState = transferState;
  }


  public TransfersIDPutResponse extensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
    return this;
  }

  /**
   * Get extensionList
   * @return extensionList
   */
  @javax.annotation.Nullable
  public ExtensionList getExtensionList() {
    return extensionList;
  }

  public void setExtensionList(@javax.annotation.Nullable ExtensionList extensionList) {
    this.extensionList = extensionList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransfersIDPutResponse transfersIDPutResponse = (TransfersIDPutResponse) o;
    return Objects.equals(this.fulfilment, transfersIDPutResponse.fulfilment) &&
        Objects.equals(this.completedTimestamp, transfersIDPutResponse.completedTimestamp) &&
        Objects.equals(this.transferState, transfersIDPutResponse.transferState) &&
        Objects.equals(this.extensionList, transfersIDPutResponse.extensionList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fulfilment, completedTimestamp, transferState, extensionList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransfersIDPutResponse {\n");
    sb.append("    fulfilment: ").append(toIndentedString(fulfilment)).append("\n");
    sb.append("    completedTimestamp: ").append(toIndentedString(completedTimestamp)).append("\n");
    sb.append("    transferState: ").append(toIndentedString(transferState)).append("\n");
    sb.append("    extensionList: ").append(toIndentedString(extensionList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("fulfilment", "completedTimestamp", "transferState", "extensionList"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("transferState"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to TransfersIDPutResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!TransfersIDPutResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in TransfersIDPutResponse is not found in the empty JSON string", TransfersIDPutResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!TransfersIDPutResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `TransfersIDPutResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : TransfersIDPutResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("fulfilment") != null && !jsonObj.get("fulfilment").isJsonNull()) && !jsonObj.get("fulfilment").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fulfilment` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fulfilment").toString()));
      }
      if ((jsonObj.get("completedTimestamp") != null && !jsonObj.get("completedTimestamp").isJsonNull()) && !jsonObj.get("completedTimestamp").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `completedTimestamp` to be a primitive type in the JSON string but got `%s`", jsonObj.get("completedTimestamp").toString()));
      }
      // validate the required field `transferState`
      TransferState.validateJsonElement(jsonObj.get("transferState"));
      // validate the optional field `extensionList`
      if (jsonObj.get("extensionList") != null && !jsonObj.get("extensionList").isJsonNull()) {
        ExtensionList.validateJsonElement(jsonObj.get("extensionList"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TransfersIDPutResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TransfersIDPutResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TransfersIDPutResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TransfersIDPutResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<TransfersIDPutResponse>() {
           @Override
           public void write(JsonWriter out, TransfersIDPutResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TransfersIDPutResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of TransfersIDPutResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of TransfersIDPutResponse
   * @throws IOException if the JSON string is invalid with respect to TransfersIDPutResponse
   */
  public static TransfersIDPutResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TransfersIDPutResponse.class);
  }

  /**
   * Convert an instance of TransfersIDPutResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

