/*
 * Copyright (c) 2024-2026 ThitsaWorks Pte. Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.api;

import com.thitsaworks.mojaloop.coreconnector.fspiop.ApiException;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.BulkTransfersIDPutResponse;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.BulkTransfersPostRequest;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformationObject;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformationResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BulkTransfersApi
 */
@Disabled
public class BulkTransfersApiTest {

    private final BulkTransfersApi api = new BulkTransfersApi();

    /**
     * Retrieve bulk transfer information
     *
     * The HTTP request &#x60;GET /bulkTransfers/{ID}&#x60; is used to get information regarding a bulk transfer created or requested earlier. The &#x60;{ID}&#x60; in the URI should contain the &#x60;bulkTransferId&#x60; that was used for the creation of the bulk transfer.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bulkTransferByIDTest() throws ApiException {
        String ID = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        String accept = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        api.bulkTransferByID(ID, contentType, date, fsPIOPSource, accept, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod);
        // TODO: test validations
    }

    /**
     * Perform bulk transfer
     *
     * The HTTP request &#x60;POST /bulkTransfers&#x60; is used to request the creation of a bulk transfer in the server.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bulkTransfersTest() throws ApiException {
        String accept = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        BulkTransfersPostRequest bulkTransfersPostRequest = null;
        Integer contentLength = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        api.bulkTransfers(accept, contentType, date, fsPIOPSource, bulkTransfersPostRequest, contentLength, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod);
        // TODO: test validations
    }

    /**
     * Return bulk transfer information
     *
     * The callback &#x60;PUT /bulkTransfers/{ID}&#x60; is used to inform the client of a requested or created bulk transfer. The &#x60;{ID}&#x60; in the URI should contain the &#x60;bulkTransferId&#x60; that was used for the creation of the bulk transfer (&#x60;POST /bulkTransfers&#x60;), or the &#x60;{ID}&#x60; that was used in the &#x60;GET /bulkTransfers/{ID}&#x60; request.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bulkTransfersByIDPutTest() throws ApiException {
        String ID = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        BulkTransfersIDPutResponse bulkTransfersIDPutResponse = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        Integer contentLength = null;
        api.bulkTransfersByIDPut(ID, contentType, date, fsPIOPSource, bulkTransfersIDPutResponse, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, contentLength);
        // TODO: test validations
    }

    /**
     * Return bulk transfer information error
     *
     * If the server is unable to find or create a bulk transfer, or another processing error occurs, the error callback &#x60;PUT /bulkTransfers/{ID}/error&#x60; is used. The &#x60;{ID}&#x60; in the URI should contain the &#x60;bulkTransferId&#x60; that was used for the creation of the bulk transfer (&#x60;POST /bulkTransfers&#x60;), or the &#x60;{ID}&#x60; that was used in the &#x60;GET /bulkTransfers/{ID}&#x60; request.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void bulkTransfersErrorByIDTest() throws ApiException {
        String ID = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        ErrorInformationObject errorInformationObject = null;
        Integer contentLength = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        api.bulkTransfersErrorByID(ID, contentType, date, fsPIOPSource, errorInformationObject, contentLength, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod);
        // TODO: test validations
    }

}
