/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.api;

import com.thitsaworks.mojaloop.coreconnector.fspiop.ApiException;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformationObject;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformationResponse;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransactionsIDPutResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransactionsApi
 */
@Disabled
public class TransactionsApiTest {

    private final TransactionsApi api = new TransactionsApi();

    /**
     * Retrieve transaction information
     *
     * The HTTP request &#x60;GET /transactions/{ID}&#x60; is used to get transaction information regarding a financial transaction created earlier. The &#x60;{ID}&#x60; in the URI should contain the &#x60;transactionId&#x60; that was used for the creation of the quote, as the transaction is created as part of another process (the transfer process).
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transactionsByIDTest() throws ApiException {
        String ID = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        String accept = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        api.transactionsByID(ID, contentType, date, fsPIOPSource, accept, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod);
        // TODO: test validations
    }

    /**
     * Return transaction information
     *
     * The callback &#x60;PUT /transactions/{ID}&#x60; is used to inform the client of a requested transaction. The &#x60;{ID}&#x60; in the URI should contain the &#x60;{ID}&#x60; that was used in the &#x60;GET /transactions/{ID}&#x60; request.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transactionsByID1Test() throws ApiException {
        String ID = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        TransactionsIDPutResponse transactionsIDPutResponse = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        Integer contentLength = null;
        api.transactionsByID1(ID, contentType, date, fsPIOPSource, transactionsIDPutResponse, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, contentLength);
        // TODO: test validations
    }

    /**
     * Return transaction information error
     *
     * If the server is unable to find or create a transaction, or another processing error occurs, the error callback &#x60;PUT /transactions/{ID}/error&#x60; is used. The &#x60;{ID}&#x60; in the URI should contain the &#x60;{ID}&#x60; that was used in the &#x60;GET /transactions/{ID}&#x60; request.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transactionsErrorByIDTest() throws ApiException {
        String ID = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        ErrorInformationObject errorInformationObject = null;
        Integer contentLength = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        api.transactionsErrorByID(ID, contentType, date, fsPIOPSource, errorInformationObject, contentLength, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod);
        // TODO: test validations
    }

}
