/*
 * Copyright (c) 2026 ThitsaWorks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Open API for FSP Interoperability (FSPIOP)
 * Revision date: 2023-11-23 Based on [API Definition updated on 2020-05-19 Version 1.1](https://github.com/mojaloop/mojaloop-specification/blob/main/documents/v1.1-document-set/API%20Definition_v1.1.pdf). This is implementation friendly version of the API definition. It includes the below definitions needed for third-party functionality. - AuthenticationType   - U2F enum - AuthenticationValue   - oneOf is changed to anyOf   - new element is added U2FPinValue - New element U2FPIN **Note:** The API supports a maximum size of 65536 bytes (64 Kilobytes) in the HTTP header.
 *
 * The version of the OpenAPI document: 2.0-draft
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.thitsaworks.mojaloop.coreconnector.fspiop.api;

import com.thitsaworks.mojaloop.coreconnector.fspiop.ApiException;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformationObject;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.ErrorInformationResponse;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransfersIDPatchResponse;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransfersIDPutResponse;
import com.thitsaworks.mojaloop.coreconnector.fspiop.model.TransfersPostRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TransfersApi
 */
@Disabled
public class TransfersApiTest {

    private final TransfersApi api = new TransfersApi();

    /**
     * Perform transfer
     *
     * The HTTP request &#x60;POST /transfers&#x60; is used to request the creation of a transfer for the next ledger, and a financial transaction for the Payee FSP.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transfersTest() throws ApiException {
        String accept = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        TransfersPostRequest transfersPostRequest = null;
        Integer contentLength = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        api.transfers(accept, contentType, date, fsPIOPSource, transfersPostRequest, contentLength, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod);
        // TODO: test validations
    }

    /**
     * Return transfer information error
     *
     * If the server is unable to find or create a transfer, or another processing error occurs, the error callback &#x60;PUT /transfers/{ID}/error&#x60; is used. The &#x60;{ID}&#x60; in the URI should contain the &#x60;transferId&#x60; that was used for the creation of the transfer, or the &#x60;{ID}&#x60; that was used in the &#x60;GET /transfers/{ID}&#x60;.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transfersByIDAndErrorTest() throws ApiException {
        String ID = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        ErrorInformationObject errorInformationObject = null;
        Integer contentLength = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        api.transfersByIDAndError(ID, contentType, date, fsPIOPSource, errorInformationObject, contentLength, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod);
        // TODO: test validations
    }

    /**
     * Retrieve transfer information
     *
     * The HTTP request &#x60;GET /transfers/{ID}&#x60; is used to get information regarding a transfer created or requested earlier. The &#x60;{ID}&#x60; in the URI should contain the &#x60;transferId&#x60; that was used for the creation of the transfer.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transfersByIDGetTest() throws ApiException {
        String ID = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        String accept = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        api.transfersByIDGet(ID, contentType, date, fsPIOPSource, accept, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod);
        // TODO: test validations
    }

    /**
     * Return transfer information
     *
     * The HTTP request PATCH /transfers/&lt;ID&gt; is used by a Switch to update the state of a previously reserved transfer, if the Payee FSP has requested a commit notification when the Switch has completed processing of the transfer. The &lt;ID&gt; in the URI should contain the transferId that was used for the creation of the transfer. Please note that this request does not generate a callback.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transfersByIDPatchTest() throws ApiException {
        String ID = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        TransfersIDPatchResponse transfersIDPatchResponse = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        Integer contentLength = null;
        api.transfersByIDPatch(ID, contentType, date, fsPIOPSource, transfersIDPatchResponse, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, contentLength);
        // TODO: test validations
    }

    /**
     * Return transfer information
     *
     * The callback &#x60;PUT /transfers/{ID}&#x60; is used to inform the client of a requested or created transfer. The &#x60;{ID}&#x60; in the URI should contain the &#x60;transferId&#x60; that was used for the creation of the transfer, or the &#x60;{ID}&#x60; that was used in the &#x60;GET /transfers/{ID}&#x60; request.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void transfersByIDPutTest() throws ApiException {
        String ID = null;
        String contentType = null;
        String date = null;
        String fsPIOPSource = null;
        TransfersIDPutResponse transfersIDPutResponse = null;
        String xForwardedFor = null;
        String fsPIOPDestination = null;
        String fsPIOPEncryption = null;
        String fsPIOPSignature = null;
        String FSPIOP_URI = null;
        String fsPIOPHTTPMethod = null;
        Integer contentLength = null;
        api.transfersByIDPut(ID, contentType, date, fsPIOPSource, transfersIDPutResponse, xForwardedFor, fsPIOPDestination, fsPIOPEncryption, fsPIOPSignature, FSPIOP_URI, fsPIOPHTTPMethod, contentLength);
        // TODO: test validations
    }

}
