name: Publish GitHub Package

on:
  release:
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          cache: maven

      - name: Publish to GitHub Packages
        run: mvn --batch-mode clean deploy
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
